#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Workflow
 * Module:  ProcessInst
 * Descrption:
 * CreateDate: 2010/11/18 14:21:45
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections.Generic;
using log4net;

using EAFrame.Core;
using EAFrame.Core.Caching;
using EAFrame.Core.Service;
using EAFrame.Core.Enums;
using EAFrame.Core.DataFilter;
using EAFrame.Workflow.Domain;

namespace EAFrame.Workflow.Service
{
    public class ProcessInstService :  BaseService<string,ProcessInst>
    {
		#region Fields
		private readonly ILog log = LogManager.GetLogger(typeof(ProcessInstService));
		#endregion
		
		#region Constructors
		
		public ProcessInstService(){ }
		#endregion

        #region IProcessInstService Imp

        #endregion
		
		#region Internal Methods

        #endregion
    }
}