#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: CMS
 * Module:  Widgets
 * Descrption:
 * CreateDate: 2011/2/16
 * Author: hgq
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using log4net;

using EAFrame.Core;
using EAFrame.Core.Caching;
using EAFrame.Core.Service;
using EAFrame.Core.Enums;
using EAFrame.Core.DataFilter;
using SunTek.CMS.Domain;

namespace SunTek.CMS.Service
{
    public class WidgetsService : BaseService<string, Widgets>
    {
        #region Fields
        private readonly ILog log = LogManager.GetLogger(typeof(WidgetsService));
        #endregion

        #region Constructors

        public WidgetsService() { }
        #endregion

        #region IResumeService Imp

        #endregion

        #region Internal Methods

        #endregion
    }
}
