#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Assessment
 * Module:  Survey
 * Descrption:
 * CreateDate: 2010/11/18 14:01:00
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Reflection;
using System.Text;

using log4net;
using Microsoft.Practices.Unity;
using EAFrame.Core;
using EAFrame.Core.Enums;
using EAFrame.Core.Service;
using EAFrame.Core.Security;
using EAFrame.Core.Extensions;
using EAFrame.Core.Web;
using EAFrame.Core.Caching;
using EAFrame.Core.Utility;
using EAFrame.Core.FastInvoker;
using EAFrame.WebControls;
using SunTek.Assessment.Domain;
using SunTek.Assessment.Service;

using SunTek.EAFrame.AuthorizeCenter.Domain;
using SunTek.EAFrame.AuthorizeCenter.Service;
using SunTek.EAFrame.ExternalInterface.Entity;
using SunTek.EAFrame.ExternalInterface.Domain;
using SunTek.EAFrame.ExternalInterface.Service;

using Newtonsoft.Json;
using System.Data;


using EAFrame.Core.Data;
using EAFrame.Core.DataFilter;

namespace WebSite
{
    public partial class SurveyExpert : BasePage
    {
        private SurveyService surveyService=new SurveyService();
        private SurveyResultService surveyResultService = new SurveyResultService();
         private ExpertService expertService = new ExpertService();
	
		#region ---界面处理方法---

       	protected bool ShowPageDetail()
        {
			if (PageContext.Action == ActionType.Add)
			{
				dtpEndTime.Text=DateTime.Now.ToShortDateString();
				//dtpCreateTime.Text=DateTime.Now.ToShortDateString();
				return false;
			}

            cboCategory.IsSingle = true;
            cboCategory.BindCombox(SubjectCategory.FullTest);

            Survey entity =surveyService.GetDomain(CurrentId);
			
            if (entity == null) return false;
            hidSurveyStatus.Value = entity.Status.ToString();//测评状态;
          
			SetControlValues(entity);
            ExamPaper examPaper = new ExamPaperService().GetDomain(entity.ExamPaperID);
            if (examPaper != null)
            {
                txtExamPaper.Text = examPaper.Title;
            }


            Employee employee = new EmployeeService().GetDomain(entity.SurveyTarget);
            if (employee != null)
            {
                txtSurveyTarget.Text = employee.Name;
            }


			return true;
        }



        /// <summary>
        /// 初始化页面
        /// </summary>
        /// <param name="e"></param>
        protected override void OnInit(EventArgs e)
        {
            base.OnInit(e);
            gvList.PageChanged += new PagedGridView.PagintEventHandler(gvList_PageChanged);
        }

        void gvList_PageChanged(object sender, PagingArgs e)
        {
            ShowList(gvList, new PageInfo(e.PageIndex, e.PageSize, e.ItemCount));
        }

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack && !IsAjaxPost)
            {
                ShowList(gvList,new PageInfo(gvList.PageIndex, gvList.PageSize, gvList.ItemCount));
            }
            ShowPageDetail();
        }

        public void ShowList(PagedGridView gvList, PageInfo pageInfo)
        {
         
            DataTable dt = expertService.GetSurveyExpert(CurrentId, pageInfo);


            gvList.IncludeRowDoubleClick = false;
            gvList.ItemCount = pageInfo.ItemCount;
            gvList.DataSource = dt;
            gvList.DataBind();

        }

        protected void cmdRefresh_Click(object sender, EventArgs e)
        {
            ShowList(gvList, new PageInfo(1, gvList.PageSize, gvList.ItemCount));
        }
		#endregion
		
		#region ---操作处理方法---
		protected Survey GetDomainObject()
		{
            Survey  survey = surveyService.GetDomain(CurrentId);

            if (survey == null)
            {
                survey = new Survey();
				survey.ID=CurrentId;
            }

			GetControlValues(ref survey);	
			
            return survey;
		}

     
        /// <summary>
        /// 保存答题人
        /// </summary>
        /// <param name="argument"></param>
        /// <returns></returns>
        public string SaveTester(string argument)
        {
            AjaxResult ajaxResult = new AjaxResult();
            Expert expert = new Expert();

            string errorMsg = string.Empty;
            ActionResult actionResult = ActionResult.Failed;
            string actionMessage = string.Empty;
            try
            {

                string userIDs = Request.Form["UserIDs"].ToSafeString().Trim('$');
                //string endTime = Request.Form["EndTime"];
                //string limitTime = Request.Form["LimitTime"];

                IList<Expert> experts = new List<Expert>();
                if (!string.IsNullOrWhiteSpace(userIDs))
                {
                    IList<string> parameters = userIDs.Split('$').ToList();
                    foreach (string para in parameters)
                    {
                        IList<string> spara = para.Split(',').ToList();
                        expert = new Expert()
                        {
                            ID = IdGenerator.NewComb().ToSafeString(),
                            //RemainTime = limitTime.ToInt(),
                            //EntTime = endTime.ToDateTime(),
                            OwnerOrg = User.OrgPath,
                            SurveyID = CurrentId,
                            Tester = "-1",//这里标识的是
                             Scorer = spara[0],
                            IsLock = 0,
                            CreateTime=DateTime.Now
                        };
                        experts.SafeAdd(expert);
                    }

                  
                }

               expertService.SaveSurveyExperts(CurrentId, experts);

                actionResult = ActionResult.Success;

                //获取提示信息
                actionMessage = RemarkAttribute.GetEnumRemark(actionResult);

                //记录操作日志
                AddActionLog(expert, PageContext.Action, actionResult, actionMessage);

                ajaxResult.ActionResult = actionResult;
                ajaxResult.RetValue = userIDs; //survey.ID;
                ajaxResult.PromptMsg = actionMessage;
            }
            catch (Exception ex)
            {
                actionMessage = RemarkAttribute.GetEnumRemark(actionResult);
                log.Error(actionMessage, ex);
            }

            return JsonConvert.SerializeObject(ajaxResult);
        }

        /// <summary>
        /// 解锁加锁
        /// </summary>
        /// <param name="argument"></param>
        /// <returns></returns>
        public string ChangeLock(string argument)
        {
            AjaxResult ajaxResult = new AjaxResult();
           
            string errorMsg = string.Empty;
            ActionResult actionResult = ActionResult.Failed;
            string actionMessage = string.Empty;
            try
            {
                string expertID = Request.Form["SurveyExpertID"];
                 Expert expert = expertService.GetDomain(expertID);
                int isLock=0;

               
                if (expert != null)
                {
                    if (expert.IsLock == 0)
                        isLock = 1;

                    expertService.ChangeLock(expertID, isLock);
                   
                    actionResult = ActionResult.Success;
                }



                //获取提示信息
                actionMessage = RemarkAttribute.GetEnumRemark(actionResult);

                //记录操作日志
                AddActionLog(expert, PageContext.Action, actionResult, actionMessage);

                ajaxResult.ActionResult = actionResult;
                ajaxResult.RetValue = isLock;
                ajaxResult.PromptMsg = actionMessage;
            }
            catch (Exception ex)
            {
                actionMessage = RemarkAttribute.GetEnumRemark(actionResult);
                log.Error(actionMessage, ex);
            }

            return JsonConvert.SerializeObject(ajaxResult);
        }

        /// <summary>
        /// 发布测试
        /// </summary>
        /// <param name="argument"></param>
        /// <returns></returns>
        public string Published(string argument)
        {
            AjaxResult ajaxResult = new AjaxResult();
            string errorMsg = string.Empty;
            ActionResult actionResult = ActionResult.Failed;
            string actionMessage = string.Empty;

            try
            {
                Survey survey = surveyService.GetDomain(argument);

                if (survey != null)
                {
                  
                   #region 发待办给待评人

                   EIACMessage eIACMessage = new EIACMessage()
                   {
                       Title = string.Format("专家评分 - {0}", survey.Title),
                       CreateTime = DateTime.Now,
                       AppProcInstID = argument,
                       Initiator=User.LoginName,
                       InitiatorName=User.Name
                   };

                   //取得测评活动相关的所有的测评人
                   IDictionary<string, object> para = new Dictionary<string, object>();
                   para.SafeAdd("SurveyID", argument);
                    para.SafeAdd("Status", new Condition("a.Status=0"));
                   // expertService.GetSurveyExpert(CurrentId, pageInfo);
                    DataTable dt = expertService.GetSurveyExpert(para, null);
                    if (dt.Rows.Count > 0)
                    {
                        foreach (DataRow dr in dt.Rows)
                        {
                            EIACWorkItem workItem = new EIACWorkItem()
                            {
                                AppWorkQueueID = (string)dr["ID"],
                                Executor = (string)dr["LoginName"],
                                ExecutorName = (string)dr["Name"],
                                CurrActivity = "评分",
                                PendingItemURL = string.Format("{0}Assessment/ExpertScoreList.aspx?Entry=Score", RootPath),
                            };
                            eIACMessage.WorkItems.Add(workItem);
                        }

                        //存进数据库
                        MessagePump message = new MessagePump()
                        {
                            CreateTime = DateTime.Now,
                            ID = IdGenerator.NewGuid().ToSafeString(),
                            MessageContent = eIACMessage.ToXml(),
                            MessageType = (short)SunTek.EAFrame.ExternalInterface.Domain.MessageType.Init,

                        };
                        // 
                        bool isSuccess = false;
                        string result = string.Empty;
                        EIAC_OA_XWorkQueue client = new EIAC_OA_XWorkQueue();
                        try
                        {
                            result = client.CreateWorkItems(message.MessageContent);
                        }
                        catch (Exception ex)
                        {

                        }
                        if (result.IndexOf("<ResultCode>0</ResultCode>") > -1)
                        {
                            isSuccess = true;
                        }
                        if (!isSuccess)
                        {
                            new MessagePumpService().SaveOrUpdate(message);
                        }
                    }

                   #endregion
                    
                    expertService.Publish(survey.ID);
                    actionResult = ActionResult.Success;
                }

                //获取提示信息
                actionMessage = RemarkAttribute.GetEnumRemark(actionResult);

                //记录操作日志
                AddActionLog(survey, PageContext.Action, actionResult, actionMessage);

                ajaxResult.ActionResult = actionResult;
                ajaxResult.RetValue = survey.ID;
                ajaxResult.PromptMsg = actionMessage;
            }
            catch (Exception ex)
            {
                actionMessage = RemarkAttribute.GetEnumRemark(actionResult);
                log.Error(actionMessage, ex);
            }

            return JsonConvert.SerializeObject(ajaxResult);
        }

        /// <summary>
        /// 删除答题人 
        /// </summary>
        /// <param name="argument"></param>
        /// <returns></returns>
        public string DelTester(string argument)
        {
            Expert expert = null;
            AjaxResult ajaxResult = new AjaxResult();

            string errorMsg = string.Empty;
            ActionResult actionResult = ActionResult.Failed;
            string actionMessage = string.Empty;
            try
            {
                argument=argument.Substring(0,argument.Length-1);
                string[] ids = argument.Split(',');
                foreach (string id in ids)
                {
                    expert = expertService.GetDomain(id);

                    if (expert != null)
                    {
                        if (expert.Status != (int)ExpertStatus.Init)
                        {
                            actionMessage = "该专家已处于评分中，无法删除！";
                        }
                        else
                        {
                            expertService.DeleteExpert(expert);
                            actionResult = ActionResult.Success;
                            //获取提示信息
                            actionMessage = RemarkAttribute.GetEnumRemark(actionResult);
                        }
                    }
                }

              

                //记录操作日志
                AddActionLog(expert, PageContext.Action, actionResult, actionMessage);

                ajaxResult.ActionResult = actionResult;
                ajaxResult.RetValue = argument;
                ajaxResult.PromptMsg = actionMessage;
            }
            catch (Exception ex)
            {
                actionMessage = RemarkAttribute.GetEnumRemark(actionResult);
                log.Error(actionMessage, ex);
            }

            return JsonConvert.SerializeObject(ajaxResult);
        }

        /// <summary>
        /// 刷新
        /// </summary>
        /// <returns></returns>
        public string RefreshGrid(string argument)
        {
            AjaxResult ajaxResult = new AjaxResult();

            string errorMsg = string.Empty;
            ActionResult actionResult = ActionResult.Failed;
            string actionMessage = string.Empty;
            try
            {
                int pageIndex=argument==null ? 1:argument.ToInt();
                var pageInfo = new PageInfo(pageIndex, gvList.PageSize, 0);
                DataTable dt = expertService.GetSurveyExpert(CurrentId, pageInfo);
                if (dt.Rows.Count==0)
                {
                    actionResult = ActionResult.Other;
                    actionMessage = "返回数据为空";
                    ajaxResult.RetValue = null;
                }
                else
                {
                    int rowsCount = dt.Rows.Count;
                    int pageCout = pageInfo.ItemCount % pageInfo.PageSize == 0 ? (pageInfo.ItemCount / pageInfo.PageSize).ToInt() : (pageInfo.ItemCount / pageInfo.PageSize + 1).ToInt();

                    actionResult = ActionResult.Success;

                    //获取提示信息
                    actionMessage = RemarkAttribute.GetEnumRemark(actionResult);

                    var ret = new
                    {
                        total = pageCout, //总页数
                        pageIndex = pageInfo.PageIndex,  //当前页
                        pageSize = pageInfo.PageSize, //每页条数
                        ItemCount = pageInfo.ItemCount, //总条数                        
                        rows = dt.ToList<SurveyTester>()
                    };
                    ajaxResult.RetValue = ret;
                }

                ajaxResult.ActionResult = actionResult;
                ajaxResult.PromptMsg = actionMessage; 

            }
            catch (Exception ex)
            {
                actionMessage = RemarkAttribute.GetEnumRemark(actionResult);
                log.Error(actionMessage, ex);
            }

            return JsonConvert.SerializeObject(ajaxResult);
        }

		#endregion
    }
}
