#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: LAMS
 * Module:  Diploma
 * Descrption:
 * CreateDate: 2010/11/18 14:11:17
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections.Generic;
using log4net;

using EAFrame.Core;
using EAFrame.Core.Caching;
using EAFrame.Core.Service;
using EAFrame.Core.Enums;
using EAFrame.Core.DataFilter;
using SunTek.LAMS.Domain;

namespace SunTek.LAMS.Service
{
    public class DiplomaService :  BaseService<string,Diploma>
    {
		#region Fields
		private readonly ILog log = LogManager.GetLogger(typeof(DiplomaService));
		#endregion
		
		#region Constructors
		
		public DiplomaService(){ }
		#endregion

        #region IDiplomaService Imp

        #endregion
		
		#region Internal Methods

        #endregion
    }
}