#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: EAFrame.Assessment
 * Module:  AssessmentRole
 * Descrption:
 * CreateDate: 2011-1-27 10:50:43
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections.Generic;
using log4net;

using EAFrame.Core;
using EAFrame.Core.Caching;
using EAFrame.Core.Service;
using EAFrame.Core.Enums;
using EAFrame.Core.DataFilter;
using SunTek.Assessment.Domain;

namespace SunTek.Assessment.Service
{
    public class AssessmentRoleService :  BaseService<string,AssessmentRole>
    {
		#region Fields
		private readonly ILog log = LogManager.GetLogger(typeof(AssessmentRoleService));
		#endregion
		
		#region Constructors
		
		public AssessmentRoleService(){ }
		#endregion

        #region IAssessmentRoleService Imp

        #endregion
		
		#region Internal Methods

        #endregion
    }
}