#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Assessment
 * Module:  ExamPaperSubject
 * Descrption:
 * CreateDate: 2010/11/18 14:00:59
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections.Generic;
using log4net;

using EAFrame.Core;
using EAFrame.Core.Caching;
using EAFrame.Core.Service;
using EAFrame.Core.Enums;
using EAFrame.Core.DataFilter;
using SunTek.Assessment.Domain;
using EAFrame.Core.Extensions;

namespace SunTek.Assessment.Service
{
    public class ExamPaperSubjectService :  BaseService<string,ExamPaperSubject>
    {
		#region Fields
		private readonly ILog log = LogManager.GetLogger(typeof(ExamPaperSubjectService));
		#endregion
		
		#region Constructors
		
		public ExamPaperSubjectService(){ }
		#endregion

        #region IExamPaperSubjectService Imp


        /// <summary>
        /// 获取问卷相关的题目
        /// </summary>
        /// <param name="userID">问卷ID</param>
        /// <returns></returns>
        public List<Subject> GetSubjectByMain(string mainId)
        {
            if (string.IsNullOrWhiteSpace(mainId)) return new List<Subject>();
            DataTable dt = repository.ExecuteDataTable<ExamPaper>(string.Format(@"select t2.[ID],t2.[SubjectTitle],t2.[SubjectType],t2.[Category],t2.[Answer],t1.SubjectScore as [DefaultScore],t2.[OwnerOrg],t2.[Creator],t2.[CreateTime],t2.[ParentID],t1.[SortOrder] from LA_ExamPaperSubject t1
join LA_Subject t2 on t1.SubjectID=t2.ID
 where t1.MainSubjectID='{0}'  order by 
SortOrder asc", mainId)) ?? new DataTable();
            return dt.ToList<Subject>();
        }

        #endregion
		
		#region Internal Methods

        #endregion
    }
}