#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: EAFrame.Assessment
 * Module:  AssessmentRole
 * Descrption:
 * CreateDate: 2011-1-27 10:50:43
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections.Generic;
using log4net;

using EAFrame.Core;
using EAFrame.Core.Caching;
using EAFrame.Core.Service;
using EAFrame.Core.Enums;
using EAFrame.Core.DataFilter;
using SunTek.Assessment.Domain;

namespace SunTek.Assessment.Service
{
    public class MarkItemService :  BaseService<string,MarkItem>
    {
		#region Fields
		private readonly ILog log = LogManager.GetLogger(typeof(ExpertService));
		#endregion
		
		#region Constructors

        public MarkItemService() { }
		#endregion

        #region IMarkItemService Imp
        public void SaveMarkItems(List<MarkItem> markItems)
        {
            using (ITransaction trans = UnitOfWork.BeginTransaction(typeof(MarkItem)))
            {
                //删除已经存在的
                repository.ExecuteSql<MarkItem>(string.Format("delete from LA_MarkItem where AssessmentResultID='{0}'", markItems[0].AssessmentResultID));

                foreach (MarkItem p in markItems)
                {
                    p.ID = string.IsNullOrWhiteSpace(p.ID) ? IdGenerator.NewComb().ToString() : p.ID;
                    repository.SaveOrUpdate(p);
                }

                //更新总数
                trans.Commit();
            }
            ClearCache(typeof(MarkItem));


        }

        #endregion

        #region Internal Methods

        #endregion
    }
}