#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Assessment
 * Module:  AnswerRecord
 * Descrption:
 * CreateDate: 2010/11/18 14:00:59
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections.Generic;
using log4net;

using EAFrame.Core;
using EAFrame.Core.Data;
using EAFrame.Core.Caching;
using EAFrame.Core.Service;
using EAFrame.Core.Enums;
using EAFrame.Core.DataFilter;
using SunTek.Assessment.Domain;
using EAFrame.Core.Extensions;

namespace SunTek.Assessment.Service
{
    public class AnswerRecordService : BaseService<string, AnswerRecord>
    {
        #region Fields
        private readonly ILog log = LogManager.GetLogger(typeof(AnswerRecordService));
        #endregion

        #region Constructors

        public AnswerRecordService() { }
        #endregion

        #region IAnswerRecordService Imp
        public IList<AnswerRecord> GetAnswerRecords(IDictionary<string, object> parameters)
        {
            string cmdText = string.Format("select T2.* from LA_SurveyResult T1 join LA_AnswerRecord T2 on T1.ID = T2.AssessmentResultID");
            return repository.ExecuteDataTable<AnswerRecord>(cmdText, parameters).ToList<AnswerRecord>();
        }

        public void SaveAnswerRecords(List<AnswerRecord> answerRecords)
        {
            using (ITransaction trans = UnitOfWork.BeginTransaction(typeof(AnswerRecord)))
            {
                //删除已经存在的
                repository.ExecuteSql<AnswerRecord>(string.Format("delete from LA_AnswerRecord where AssessmentResultID='{0}'", answerRecords[0].AssessmentResultID));

                foreach (AnswerRecord p in answerRecords)
                {
                    p.ID = string.IsNullOrWhiteSpace(p.ID) ? IdGenerator.NewComb().ToString() : p.ID;
                    p.Anwser = p.Anwser.Trim(',');
                    repository.SaveOrUpdate(p);
                }

                //更新总数
                trans.Commit();
            }
            ClearCache(typeof(AnswerRecord));

            
        }

        #endregion

        #region Internal Methods

        #endregion
    }
}