#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: AuthorizeCenter
 * Module:  ObjectRole
 * Descrption:
 * CreateDate: 2010/11/18 13:55:36
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections.Generic;
using log4net;


using EAFrame.Core;
using EAFrame.Core.Data;
using EAFrame.Core.Caching;
using EAFrame.Core.Service;
using EAFrame.Core.Enums;
using EAFrame.Core.DataFilter;
using SunTek.EAFrame.AuthorizeCenter.Domain;

namespace SunTek.EAFrame.AuthorizeCenter.Service
{
    public class ObjectRoleService :  BaseService<string,ObjectRole>
    {
		#region Fields
		private readonly ILog log = LogManager.GetLogger(typeof(ObjectRoleService));
		#endregion
		
		#region Constructors
		
		public ObjectRoleService(){ }
		#endregion

        #region IObjectRoleService Imp
        public void SaveObjectRoles( IList<ObjectRole> objectRoles)
        {

            using (ITransaction trans = UnitOfWork.BeginTransaction(typeof(ObjectRole)))
            {
                //删除已经存在的
                repository.ExecuteSql<ObjectRole>(string.Format("delete from OM_ObjectRole where ObjectID='{0}'", objectRoles[0].ObjectID));
          

                foreach (var p in objectRoles)
                {
                    repository.SaveOrUpdate(p);
                }
                trans.Commit();
            }
            ClearCache(typeof(ObjectRole));
        }
        #endregion
		
		#region Internal Methods

        #endregion
    }
}