#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: AuthorizeCenter
 * Module:  Organization
 * Descrption:
 * CreateDate: 2010/11/18 13:55:37
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections.Generic;
using System.Linq;

using log4net;
using EAFrame.Core;
using EAFrame.Core.Caching;
using EAFrame.Core.Service;
using EAFrame.Core.Enums;
using EAFrame.Core.DataFilter;
using EAFrame.Core.Utility;
using EAFrame.Core.Extensions;
using EAFrame.Core.Data;
using SunTek.EAFrame.AuthorizeCenter.Domain;

namespace SunTek.EAFrame.AuthorizeCenter.Service
{
    public class OrganizationService : BaseService<string, Organization>
    {
        #region Fields
        private readonly ILog log = LogManager.GetLogger(typeof(OrganizationService));
        #endregion

        #region Constructors

        public OrganizationService() { }
        #endregion

        #region IOrganizationService Imp
        /// <summary>
        /// 获取顶级组织到当前组织的层级路径,以/分隔
        /// </summary>
        /// <param name="orgID"></param>
        public string GetOrgPath(string orgID)
        {
            var func = ExpressionUtil.MakeRecursion<string, string>(f => r =>
            {
                Organization org = new OrganizationService().All().FirstOrDefault(o => o.ID == r);
                if (org == null)
                    return string.Empty;

                if (string.IsNullOrEmpty(org.ParentID) || org.ParentID == "-1")
                    return org.ID;

                return string.Format("{0}/{1}", f(org.ParentID), org.ID);
            });

            return func(orgID);
        }

        /// <summary>
        /// 获取组织下的所有员工
        /// </summary>
       /// <param name="orgID">组织ID</param>
        /// <returns></returns>
        public IList<Employee> GetEmployees(string orgID)
        {
            IDictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.SafeAdd("ID", new Condition(string.Format("ID in (select b.EmployeeID from OM_EmployeeOrg b where b.OrgID='{0}')", orgID)));

            return repository.FindAll<Employee>(parameters);
        }

        /// <summary>
        /// 获取员工所在部门名称
        /// </summary>
        /// <param name="orgID">组织ID</param>
        /// <returns></returns>
        public IList<Organization> GetOrgNameByUserID(string userID)
        {
            IDictionary<string, object> parameters = new Dictionary<string, object>();
            parameters.SafeAdd("ID", new Condition(string.Format("ID in (select b.OrgID from OM_EmployeeOrg b where b.EmployeeID='{0}')", userID)));

            return repository.FindAll<Organization>(parameters);
        }
        #endregion

        #region Internal Methods

        #endregion
    }
}