#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: CMS
 * Module:  ContentManagement
 * Descrption:
 * CreateDate: 2011/2/21
 * Author: hgq
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using log4net;

using EAFrame.Core;
using EAFrame.Core.Caching;
using EAFrame.Core.Service;
using EAFrame.Core.Enums;
using EAFrame.Core.DataFilter;
using SunTek.CMS.Domain;
using EAFrame.Core.Extensions;


namespace SunTek.CMS.Service
{
    public class ContentManagementService : BaseService<string, ContentManagement>
    {
        #region Fields
        private readonly ILog log = LogManager.GetLogger(typeof(ContentManagementService));
        #endregion

        #region Constructors

        public ContentManagementService() { }
        #endregion

        #region IContentManagementService Imp
        /// <summary>
        /// 获取所有发布内容
        /// </summary>
        /// <param name="number">每个部件显示条数</param>
        /// <returns></returns>
        public IList<ContentManagement> GetAllContent(int number)
        {
            try
            {
                StringBuilder cmdText = new StringBuilder();
                cmdText.Append(string.Format(@"select *
                                from (
                                    select a.*,rn=row_number()over(partition by a.widgetsCode order by a.publishedTime desc)
                                    from CM_ContentManagement a 
                                    join cm_widgets b on a.widgetsCode=b.Code 
                                    where b.IsShow=1 and a.IsPublished=1 and a.IsDeleted=0
                                ) as t 
                                where rn <={0}",number));
                return repository.ExecuteDataTable<ContentManagement>(cmdText.ToString()).ToList<ContentManagement>();
            }
            catch (Exception ex)
            {
                log.Error("获取所有发布内容出错！", ex);
                return null;
            }
        }

        /// <summary>
        /// 获取某一部件下的所有内容
        /// </summary>
        /// <param name="widgetsCode"></param>
        /// <returns></returns>
        public IList<ContentManagement> GetAllContentByWidgetsCode(string widgetsCode,PageInfo pageInfo)
        {
            try
            {
                StringBuilder cmdText = new StringBuilder();
                cmdText.Append(string.Format(@"select a.* from CM_ContentManagement a
                                            join cm_widgets b on a.widgetsCode=b.Code 
                                    where a.WidgetsCode='{0}' and b.IsShow=1 and a.IsPublished=1 and a.IsDeleted=0 ", widgetsCode));
                return repository.ExecuteDataTable<ContentManagement>(cmdText.ToString(),null," PublishedTime desc",pageInfo).ToList<ContentManagement>();
                //return repository.ExecuteDataTable<ContentManagement>(cmdText.ToString()).ToList<ContentManagement>();
            }
            catch (Exception ex)
            {
                log.Error("获取所有发布内容出错！", ex);
                return null;
            }
        }
        #endregion

        #region Internal Methods

        #endregion
    }
}
