#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: CMS
 * Module:  ContentManagement
 * Descrption:
 * CreateDate: 2011/2/21
 * Author: hgq
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.CMS.Domain
{
    public partial class ContentManagement : DomainObject<string>
    {
        public ContentManagement() { }
        public virtual string WidgetsCode { get; set; }
        public virtual string Title { get; set; }
        public virtual string Description { get; set; }
        public virtual string Content { get; set; }
        public virtual short IsMain { get; set; }
        public virtual short IsPublished { get; set; }
        public virtual short IsDeleted { get; set; }
        public virtual short IsCommentsenabled { get; set; }
        public virtual string Tags { get; set; }
        public virtual string author { get; set; }
        public virtual DateTime PublishedTime { get; set; }
        public virtual DateTime lastModifiedTime { get; set; }
        public virtual string Creator { get; set; }
        public virtual DateTime CreateTime { get; set; }
    }
}
