#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: CMS
 * Module:  Widgets
 * Descrption:
 * CreateDate: 2011/2/16
 * Author: hgq
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.CMS.Domain
{
    public partial class Widgets : DomainObject<string>
    {
        public Widgets() { }
        public virtual string Code { get; set; }
        public virtual string Name { get; set; }
        public virtual short AddType { get; set; }
        public virtual string URL { get; set; }
        public virtual string Description { get; set; }
        public virtual short IsShow { get; set; }
        public virtual short Movable { get; set; }
        public virtual short Removable { get; set; }
        public virtual short Closeconfirm { get; set; }
        public virtual short Collapsable { get; set; }
        public virtual short Editable { get; set; }
        public virtual string Creator { get; set; }
        public virtual DateTime CreateTime { get; set; }


    }
}
