#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Infrastructure
 * Module:  ActionLog
 * Descrption:
 * CreateDate: 2010/11/18 13:40:07
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections.Generic;
using log4net;

using EAFrame.Core;
using EAFrame.Core.Caching;
using EAFrame.Core.Service;
using EAFrame.Core.Enums;
using EAFrame.Core.DataFilter;
using SunTek.EAFrame.Infrastructure.Domain;

namespace SunTek.EAFrame.Infrastructure.Service
{
    public class ActionLogService :  BaseService<string,ActionLog>
    {
		#region Fields
		private readonly ILog log = LogManager.GetLogger(typeof(ActionLogService));
		#endregion
		
		#region Constructors
		
		public ActionLogService(){ }
		#endregion

        #region IActionLogService Imp

        #endregion
		
		#region Internal Methods

        #endregion
    }
}