#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: EAFrame.Infrastructure
 * Module:  Catalog
 * Descrption:
 * CreateDate: 2010/12/27 20:19:51
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections.Generic;
using log4net;

using EAFrame.Core;
using EAFrame.Core.Caching;
using EAFrame.Core.Service;
using EAFrame.Core.Enums;
using EAFrame.Core.DataFilter;
using SunTek.EAFrame.Infrastructure.Domain;

namespace SunTek.EAFrame.Infrastructure.Service
{
    public class CatalogService :  BaseService<string,Catalog>
    {
		#region Fields
		private readonly ILog log = LogManager.GetLogger(typeof(CatalogService));
		#endregion
		
		#region Constructors
		
		public CatalogService(){ }
		#endregion

        #region ICatalogService Imp

        #endregion
		
		#region Internal Methods

        #endregion
    }
}