//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
namespace WebSite
{
    using System;
    using System.ComponentModel;
    using System.Diagnostics;
    using System.Web.Services;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;

    // 
    // 此源代码由 wsdl 自动生成, Version=2.0.50727.42。
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name = "EIAC_OA_XWorkQueueSoap", Namespace = "http://oa.gdeiac.com")]
    public partial class EIAC_OA_XWorkQueue : System.Web.Services.Protocols.SoapHttpClientProtocol
    {

        private System.Threading.SendOrPostCallback CreateWorkItemsOperationCompleted;

        private System.Threading.SendOrPostCallback DeleteWorkItemOperationCompleted;

        /// <remarks/>
        public EIAC_OA_XWorkQueue()
        {
            this.Url = "http://gdeiac-test06.gdeiac.local:8899/EIAC_XWorkqueue8/EIAC_OA_XWorkQueue.asmx";
        }

        /// <remarks/>
        public event CreateWorkItemsCompletedEventHandler CreateWorkItemsCompleted;

        /// <remarks/>
        public event DeleteWorkItemCompletedEventHandler DeleteWorkItemCompleted;

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://oa.gdeiac.com/CreateWorkItems", RequestNamespace = "http://oa.gdeiac.com", ResponseNamespace = "http://oa.gdeiac.com", Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        public string CreateWorkItems(string XmlData)
        {
            object[] results = this.Invoke("CreateWorkItems", new object[] {
                    XmlData});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginCreateWorkItems(string XmlData, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("CreateWorkItems", new object[] {
                    XmlData}, callback, asyncState);
        }

        /// <remarks/>
        public string EndCreateWorkItems(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void CreateWorkItemsAsync(string XmlData)
        {
            this.CreateWorkItemsAsync(XmlData, null);
        }

        /// <remarks/>
        public void CreateWorkItemsAsync(string XmlData, object userState)
        {
            if ((this.CreateWorkItemsOperationCompleted == null))
            {
                this.CreateWorkItemsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCreateWorkItemsOperationCompleted);
            }
            this.InvokeAsync("CreateWorkItems", new object[] {
                    XmlData}, this.CreateWorkItemsOperationCompleted, userState);
        }

        private void OnCreateWorkItemsOperationCompleted(object arg)
        {
            if ((this.CreateWorkItemsCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CreateWorkItemsCompleted(this, new CreateWorkItemsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("http://oa.gdeiac.com/DeleteWorkItem", RequestNamespace = "http://oa.gdeiac.com", ResponseNamespace = "http://oa.gdeiac.com", Use = System.Web.Services.Description.SoapBindingUse.Literal)]
        public string DeleteWorkItem(string XmlData)
        {
            object[] results = this.Invoke("DeleteWorkItem", new object[] {
                    XmlData});
            return ((string)(results[0]));
        }

        /// <remarks/>
        public System.IAsyncResult BeginDeleteWorkItem(string XmlData, System.AsyncCallback callback, object asyncState)
        {
            return this.BeginInvoke("DeleteWorkItem", new object[] {
                    XmlData}, callback, asyncState);
        }

        /// <remarks/>
        public string EndDeleteWorkItem(System.IAsyncResult asyncResult)
        {
            object[] results = this.EndInvoke(asyncResult);
            return ((string)(results[0]));
        }

        /// <remarks/>
        public void DeleteWorkItemAsync(string XmlData)
        {
            this.DeleteWorkItemAsync(XmlData, null);
        }

        /// <remarks/>
        public void DeleteWorkItemAsync(string XmlData, object userState)
        {
            if ((this.DeleteWorkItemOperationCompleted == null))
            {
                this.DeleteWorkItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteWorkItemOperationCompleted);
            }
            this.InvokeAsync("DeleteWorkItem", new object[] {
                    XmlData}, this.DeleteWorkItemOperationCompleted, userState);
        }

        private void OnDeleteWorkItemOperationCompleted(object arg)
        {
            if ((this.DeleteWorkItemCompleted != null))
            {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteWorkItemCompleted(this, new DeleteWorkItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }

        /// <remarks/>
        public new void CancelAsync(object userState)
        {
            base.CancelAsync(userState);
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void CreateWorkItemsCompletedEventHandler(object sender, CreateWorkItemsCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CreateWorkItemsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal CreateWorkItemsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    public delegate void DeleteWorkItemCompletedEventHandler(object sender, DeleteWorkItemCompletedEventArgs e);

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "2.0.50727.42")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteWorkItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs
    {

        private object[] results;

        internal DeleteWorkItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) :
            base(exception, cancelled, userState)
        {
            this.results = results;
        }

        /// <remarks/>
        public string Result
        {
            get
            {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}
