#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: LAMS
 * Module:  CandidateManager
 * Descrption:
 * CreateDate: 2010-11-2 21:36:51
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using log4net;

using SunTek.EAFrame.Core;
using SunTek.EAFrame.Core.Data;
using SunTek.LAMS.Domain;
using SunTek.EAFrame.Core.Extensions;


namespace SunTek.LAMS.Repository
{
    public class CandidateManagerRepository :Repository<string, CandidateManager>
    {
		#region Fields
		private static readonly ILog log = LogManager.GetLogger(typeof(CandidateManagerRepository));
		#endregion
		
		#region Constructors
        public CandidateManagerRepository(){}
		#endregion

        #region ICandidateManagerRepository Imp
        public bool SaveCandidateManager(CandidateManagerModel model)
        {
            try
            {
                foreach (var item in model.CandidateManagers)
                {
                    //if (item.PostDate != null && item.PostDate != string.Empty)
                    //{
                    item.ID = IdGenerator.NewComb().ToSafeString();
                    item.Creator = model.Creator;
                    item.CreateTime = model.CreateTime;
                    item.EmployeeID = model.Creator;
                    Session.SaveOrUpdate(item);
                    //}
                }

            }
            catch (Exception ex)
            {
                log.Error(string.Format("导入Excel数据,保存二级经理后备队伍近推荐人出错,员工Code={0}", model.EmployeeID), ex);
                return false;
            }
            return true;
        }
        #endregion
		
		#region Internal Methods

        #endregion
    }
}