#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: LAMS
 * Module:  FamilyMember
 * Descrption:
 * CreateDate: 2010-11-2 21:36:52
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections;
using System.Collections.Generic;
using log4net;

using SunTek.EAFrame.Core;
using SunTek.EAFrame.Core.Data;
using SunTek.LAMS.Domain;

namespace SunTek.LAMS.Repository
{
    public class FamilyMemberRepository :Repository<string, FamilyMember>
    {
		#region Fields
		private static readonly ILog log = LogManager.GetLogger(typeof(FamilyMemberRepository));
		#endregion
		
		#region Constructors
        public FamilyMemberRepository(){}
		#endregion

        #region IFamilyMemberRepository Imp
        #endregion
		
		#region Internal Methods

        #endregion
    }
}