//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Suntek.SAPService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.168.0.8:8081/IASService.asmx")]
        public string Suntek_SAPService_IASService_IASService {
            get {
                return ((string)(this["Suntek_SAPService_IASService_IASService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://192.1.2.203/KP_WebService/KP_WebService.asmx")]
        public string Suntek_SAPService_KP_WebService_KP_WebService {
            get {
                return ((string)(this["Suntek_SAPService_KP_WebService_KP_WebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ESHORE.EAI.ESS.WS/ESS_GET_WS.asmx")]
        public string Suntek_SAPService_ESS_GET_WS_local_ESS_GET_WS {
            get {
                return ((string)(this["Suntek_SAPService_ESS_GET_WS_local_ESS_GET_WS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://gdeiac-test06.gdeiac.local:8899/EIAC_XWorkqueue8/EIAC_OA_XWorkQueue.asmx")]
        public string Suntek_SAPService_EIAC_OA_XWorkQueue_EIAC_OA_XWorkQueue {
            get {
                return ((string)(this["Suntek_SAPService_EIAC_OA_XWorkQueue_EIAC_OA_XWorkQueue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/EIAC_XWorkqueue/EIAC_OA_XWorkQueue.asmx")]
        public string Suntek_SAPService_OA_XWorkQueue_local_EIAC_OA_XWorkQueue {
            get {
                return ((string)(this["Suntek_SAPService_OA_XWorkQueue_local_EIAC_OA_XWorkQueue"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.16.25.81/ESHORE.EAI.ESS.WS/ESS_GET_WS.asmx")]
        public string Suntek_SAPService_ESS_GET_WS_ESS_GET_WS {
            get {
                return ((string)(this["Suntek_SAPService_ESS_GET_WS_ESS_GET_WS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://10.16.25.81/ESHORE.EAI.ESS.WS/ESS_GET_WS.asmx")]
        public string Longtek_HR_CMMS_ServiceAgent_ESS_GET_WS_ESS_GET_WS {
            get {
                return ((string)(this["Longtek_HR_CMMS_ServiceAgent_ESS_GET_WS_ESS_GET_WS"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://localhost/ESHORE.EAI.ESS.WS/ESS_GET_WS.asmx")]
        public string Longtek_HR_CMMS_ServiceAgent_ESS_GET_WS_local_ESS_GET_WS {
            get {
                return ((string)(this["Longtek_HR_CMMS_ServiceAgent_ESS_GET_WS_local_ESS_GET_WS"]));
            }
        }
    }
}
