#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: CMS
 * Module:  ContentDetail
 * Descrption:
 * CreateDate: 2011/2/21
 * Author: hgq
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

using log4net;
using Microsoft.Practices.Unity;
using EAFrame.Core;
using EAFrame.Core.Enums;
using EAFrame.Core.Service;
using EAFrame.Core.Security;
using EAFrame.Core.Extensions;
using EAFrame.Core.Web;
using EAFrame.Core.Caching;
using EAFrame.Core.Utility;
using EAFrame.Core.FastInvoker;
using EAFrame.WebControls;
using SunTek.CMS.Domain;
using SunTek.CMS.Service;
using EAFrame.Core.Data;

namespace WebSite
{
    public partial class ContentDetail : BasePage
    {
        private ContentManagementService contentManagementService = new ContentManagementService();
        #region ---界面处理方法---

        protected bool ShowPageDetail()
        {
            if (PageContext.Action == ActionType.Add)
            {
                dtpCreateTime.Text = DateTime.Now.ToShortDateString();
                txtCreator.Text = User.Name;
                txtPublishedTime.Text= DateTime.Now.ToString("yyyy-MM-dd HH:mm");
                txtAuthor.Text = User.Name;
                return false;
            }

            SunTek.CMS.Domain.ContentManagement entity = contentManagementService.GetDomain(CurrentId);

            if (entity == null) return false;

            SetControlValues(entity);
            txtContent.Text = entity.Content;
            txtPublishedTime.Text = entity.PublishedTime.ToString("yyyy-MM-dd HH:mm");
            cboIsCommentsenabled.Checked = entity.IsCommentsenabled==1 ? true:false;
            cboIsPublished.Checked = entity.IsPublished == 1 ? true : false;
            cboIsMain.Checked = entity.IsMain == 1 ? true : false;

            return true;
        }

        private void bindCbo()
        {
            IDictionary<string,object> dic=new Dictionary<string,object>();
            dic.Add("AddType", "0");
            dic.Add("IsShow", "1");
            IList<Widgets> widgets = new WidgetsService().FindAll(dic);
            cboWidgetsCode.DataTextField = "Name";
            cboWidgetsCode.DataValueField = "Code";
            cboWidgetsCode.DataSource = widgets;
            cboWidgetsCode.DataBind();
        }
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack && !IsAjaxPost)
            {
                ShowPageDetail();
                bindCbo();
            }
        }
        #endregion

        #region ---操作处理方法---
        protected SunTek.CMS.Domain.ContentManagement GetDomainObject()
        {
            SunTek.CMS.Domain.ContentManagement contentManagement = contentManagementService.GetDomain(CurrentId);

            if (contentManagement == null)
            {
                contentManagement = new SunTek.CMS.Domain.ContentManagement();
                contentManagement.ID = CurrentId;
            }

            GetControlValues(ref contentManagement);

            contentManagement.Content = txtContent.Text;
            contentManagement.lastModifiedTime = DateTime.Now;
            contentManagement.IsCommentsenabled =(short) (cboIsCommentsenabled.Checked ? 1 : 0);
            contentManagement.IsPublished =(short) (cboIsPublished.Checked ? 1 : 0);
            contentManagement.IsMain = (short)(cboIsMain.Checked ? 1 : 0);


            return contentManagement;
        }

        public void Save(string argument)
        {
            try
            {
                ContentManagement contentManagement = GetDomainObject();

                contentManagementService.SaveOrUpdate(contentManagement);

                IDictionary<string, object> dic = new Dictionary<string, object>();
                dic.Add("WidgetsCode", contentManagement.WidgetsCode);
                dic.Add("IsMain", 1);
                dic.Add("ID", new Condition(" ID!='" + contentManagement.ID+"'"));
                ContentManagement MainContent = contentManagementService.FindOne(dic);
                if (MainContent != null)
                {
                    MainContent.IsMain = 0;
                    contentManagementService.SaveOrUpdate(MainContent);
                }

                WebUtil.ExecuteJs(" window.opener.location=window.opener.location; "); //window.opener.location.reload()会提示页面过期。
                WebUtil.PromptMsg("保存操作成功");
            }
            catch (Exception ex)
            {
                log.Error("保存操作失败", ex);

                WebUtil.PromptMsg("保存操作失败");
            }
        }

        #endregion
    }
}