#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Widgets
 * Module:  Widgets
 * Descrption:
 * CreateDate: 2011/2/16
 * Author: hgq
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;

using log4net;
using Microsoft.Practices.Unity;
using EAFrame.Core;
using EAFrame.Core.Enums;
using EAFrame.Core.Service;
using EAFrame.Core.Security;
using EAFrame.Core.Extensions;
using EAFrame.Core.Web;
using EAFrame.Core.Caching;
using EAFrame.Core.Utility;
using EAFrame.Core.FastInvoker;
using EAFrame.WebControls;
using SunTek.CMS.Domain;
using SunTek.CMS.Service;

namespace WebSite
{
    public partial class WidgetsDetail : BasePage
    {
        private WidgetsService widgetsService = new WidgetsService();
        #region ---界面处理方法---

        protected bool ShowPageDetail()
        {
            if (PageContext.Action == ActionType.Add)
            {
                dtpCreateTime.Text = DateTime.Now.ToShortDateString();
                txtCreator.Text = User.Name;
                return false;
            }

            SunTek.CMS.Domain.Widgets entity = widgetsService.GetDomain(CurrentId);

            if (entity == null) return false;

            SetControlValues(entity);

            return true;
        }
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack && !IsAjaxPost)
            {
                ShowPageDetail();
            }
        }
        #endregion

        #region ---操作处理方法---
        protected SunTek.CMS.Domain.Widgets GetDomainObject()
        {
            SunTek.CMS.Domain.Widgets widgets = widgetsService.GetDomain(CurrentId);

            if (widgets == null)
            {
                widgets = new SunTek.CMS.Domain.Widgets();
                widgets.ID = CurrentId;
            }

            GetControlValues(ref widgets);

            return widgets;
        }

        public void Save(string argument)
        {
            try
            {
                SunTek.CMS.Domain.Widgets widgets = GetDomainObject();
                IDictionary<string, object> dic = new Dictionary<string, object>();
                dic.Add("Code", widgets.Code);
                Widgets model = widgetsService.FindOne(dic);
                if (model != null && model.ID!=widgets.ID)
                {
                    WebUtil.PromptMsg("已存在相同部件名的部件！");
                    return;
                }

                widgetsService.SaveOrUpdate(widgets);

                WebUtil.PromptMsg("保存操作成功");
            }
            catch (Exception ex)
            {
                log.Error("保存操作失败", ex);

                WebUtil.PromptMsg("保存操作失败");
            }
        }

        #endregion
    }
}