#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: LAMS
 * Module:  CandidateDetail
 * Descrption:
 * CreateDate: 2010/11/18 14:11:16
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.LAMS.Domain
{
    public partial class CandidateDetail :DomainObject<string>
    {
        #region Fields
		
		private string _code = string.Empty;
		private int _shouldCount = default(Int32);
		private int _attendCount = default(Int32);
		private int _employeeCount = default(Int32);
		private int _approveCount = default(Int32);
		private double _approvePercent = default(Double);
		private string _majorKPI = string.Empty;
		private string _deficiency = string.Empty;
		private string _trainingPlan = string.Empty;
		private string _recommendation = string.Empty;
		private string _creator = string.Empty;
		private System.DateTime _createTime = DateTime.Now;
		
		
        #endregion

        #region Constructors
		public CandidateDetail(){}
		
		
		public CandidateDetail(string id,string code,int shouldCount,int attendCount,int employeeCount,int approveCount,double approvePercent,string majorKPI,string deficiency,string trainingPlan,string recommendation,string creator,System.DateTime createTime)
		{
		  this.ID=id;
		this._code=code;
		this._shouldCount=shouldCount;
		this._attendCount=attendCount;
		this._employeeCount=employeeCount;
		this._approveCount=approveCount;
		this._approvePercent=approvePercent;
		this._majorKPI=majorKPI;
		this._deficiency=deficiency;
		this._trainingPlan=trainingPlan;
		this._recommendation=recommendation;
		this._creator=creator;
		this._createTime=createTime;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_code);
			sb.Append(_shouldCount);
			sb.Append(_attendCount);
			sb.Append(_employeeCount);
			sb.Append(_approveCount);
			sb.Append(_approvePercent);
			sb.Append(_majorKPI);
			sb.Append(_deficiency);
			sb.Append(_trainingPlan);
			sb.Append(_recommendation);
			sb.Append(_creator);
			sb.Append(_createTime);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 员工编号
        /// </summary>
		public virtual string Code
        {
            get { return  _code; }
            set { _code = value; }
        }
		
		/// <summary>
        /// 应到人数
        /// </summary>
		public virtual int ShouldCount
        {
            get { return  _shouldCount; }
			set	{	_shouldCount =  value;}
        }
		
		/// <summary>
        /// 实到人数
        /// </summary>
		public virtual int AttendCount
        {
            get { return  _attendCount; }
			set	{	_attendCount =  value;}
        }
		
		/// <summary>
        /// 员工代表人数
        /// </summary>
		public virtual int EmployeeCount
        {
            get { return  _employeeCount; }
			set	{	_employeeCount =  value;}
        }
		
		/// <summary>
        /// 同意票数
        /// </summary>
		public virtual int ApproveCount
        {
            get { return  _approveCount; }
			set	{	_approveCount =  value;}
        }
		
		/// <summary>
        /// 占票数百分比
        /// </summary>
		public virtual double ApprovePercent
        {
            get { return  _approvePercent; }
			set	{	_approvePercent =  value;}
        }
		
		/// <summary>
        /// 主要业绩
        /// </summary>
		public virtual string MajorKPI
        {
            get { return  _majorKPI; }
			set	{	_majorKPI =  value;}
        }
		
		/// <summary>
        /// 主要不足
        /// </summary>
		public virtual string Deficiency
        {
            get { return  _deficiency; }
			set	{	_deficiency =  value;}
        }
		
		/// <summary>
        /// 培训发展计划
        /// </summary>
		public virtual string TrainingPlan
        {
            get { return  _trainingPlan; }
			set	{	_trainingPlan =  value;}
        }
		
		/// <summary>
        /// 推荐意见
        /// </summary>
		public virtual string Recommendation
        {
            get { return  _recommendation; }
			set	{	_recommendation =  value;}
        }
		
		/// <summary>
        /// 创建者
        /// </summary>
		public virtual string Creator
        {
            get { return  _creator; }
			set	{	_creator =  value;}
        }
		
		/// <summary>
        /// 创建时间
        /// </summary>
		public virtual System.DateTime CreateTime
        {
            get { return  _createTime.ToSafeDateTime(); }
			set	{	_createTime =  value.ToSafeDateTime();}
        }
		
        #endregion
    }
}
