#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: LAMS
 * Module:  Resume
 * Descrption:
 * CreateDate: 2010/11/18 14:11:17
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.LAMS.Domain
{
    public partial class Resume :DomainObject<string>
    {
        #region Fields
		
		private string _employeeID = string.Empty;
		private string _startDate = string.Empty;
		private string _endDate = string.Empty;
		private string _workplace = string.Empty;
		private string _position = string.Empty;
		private string _creator = string.Empty;
		private System.DateTime _createTime = DateTime.Now;
		
		
        #endregion

        #region Constructors
		public Resume(){}
		
		
		public Resume(string id,string employeeID,string startDate,string endDate,string workplace,string position,string creator,System.DateTime createTime)
		{
		  this.ID=id;
		this._employeeID=employeeID;
		this._startDate=startDate;
		this._endDate=endDate;
		this._workplace=workplace;
		this._position=position;
		this._creator=creator;
		this._createTime=createTime;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_employeeID);
			sb.Append(_startDate);
			sb.Append(_endDate);
			sb.Append(_workplace);
			sb.Append(_position);
			sb.Append(_creator);
			sb.Append(_createTime);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 员工编号
        /// </summary>
		public virtual string EmployeeID
        {
            get { return  _employeeID; }
			set	{	_employeeID =  value;}
        }
		
		/// <summary>
        /// 起始时间
        /// </summary>
		public virtual string StartDate
        {
            get { return  _startDate; }
			set	{	_startDate =  value;}
        }
		
		/// <summary>
        /// 结束时间
        /// </summary>
		public virtual string EndDate
        {
            get { return  _endDate; }
			set	{	_endDate =  value;}
        }
		
		/// <summary>
        /// 学习/工作地点
        /// </summary>
		public virtual string Workplace
        {
            get { return  _workplace; }
			set	{	_workplace =  value;}
        }
		
		/// <summary>
        /// 职务
        /// </summary>
		public virtual string Position
        {
            get { return  _position; }
			set	{	_position =  value;}
        }
		
		/// <summary>
        /// 创建者
        /// </summary>
		public virtual string Creator
        {
            get { return  _creator; }
			set	{	_creator =  value;}
        }
		
		/// <summary>
        /// 创建时间
        /// </summary>
		public virtual System.DateTime CreateTime
        {
            get { return  _createTime.ToSafeDateTime(); }
			set	{	_createTime =  value.ToSafeDateTime();}
        }
		
        #endregion
    }
}
