#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: LAMS
 * Module:  CandidateManager
 * Descrption:
 * CreateDate: 2010/11/18 14:11:16
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.LAMS.Domain
{
    public partial class CandidateManager :DomainObject<string>
    {
        #region Fields
		
		private string _code = string.Empty;
		private string _targetCandidate = string.Empty;
		private string _inPostDate = string.Empty;
		private string _inGradeDate = string.Empty;
		private int _tenure = default(Int32);
		private string _candidateMaturity = string.Empty;
		private int _candidateOrder = default(Int32);
        private Double _democracyPecent = default(Double);
		private short _isAnomalous = default(Int16);
		private string _assessment1 = string.Empty;
		private string _assessment2 = string.Empty;
		private string _assessment3 = string.Empty;
		private string _creator = string.Empty;
		private System.DateTime _createTime = DateTime.Now;
        private short _isChief = default(Int16);
        private string _candidatePostGrade = string.Empty;
        private string _candidateManagerGrade = string.Empty;
        private string _candidatePost = string.Empty;
        private short _status = default(Int16);
        private DateTime _initTime = DateTime.Now;
        private string _initor = string.Empty;
        private short _isPresident = default(Int16);
		
        #endregion

        #region Constructors
		public CandidateManager(){}
		
		
		public CandidateManager(string id,string code,string targetCandidate,
            string inPostDate,string inGradeDate,int tenure,string candidateMaturity,
            int candidateOrder, double democracyPecent, short isAnomalous, string assessment1,
            string assessment2,string assessment3,string creator,System.DateTime createTime,
            short isChief, string candidatePostGrade, string candidateManagerGrade, string candidatePost,
            short status,DateTime initTime,string initor,short isPresident)
		{
		  this.ID=id;
		this._code=code;
		this._targetCandidate=targetCandidate;
		this._inPostDate=inPostDate;
		this._inGradeDate=inGradeDate;
		this._tenure=tenure;
		this._candidateMaturity=candidateMaturity;
		this._candidateOrder=candidateOrder;
        this._democracyPecent = democracyPecent;
		this._isAnomalous=isAnomalous;
		this._assessment1=assessment1;
		this._assessment2=assessment2;
		this._assessment3=assessment3;
		this._creator=creator;
		this._createTime=createTime;
        this._isChief = isChief;
        this._candidatePostGrade = candidatePostGrade;
        this._candidateManagerGrade = candidateManagerGrade;
        this._candidatePost = candidatePost;
        this._status = status;
        this._initTime = initTime;
        this._initor = initor;
        this._isPresident = isPresident;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_code);
			sb.Append(_targetCandidate);
			sb.Append(_inPostDate);
			sb.Append(_inGradeDate);
			sb.Append(_tenure);
			sb.Append(_candidateMaturity);
			sb.Append(_candidateOrder);
            sb.Append(_democracyPecent);
			sb.Append(_isAnomalous);
			sb.Append(_assessment1);
			sb.Append(_assessment2);
			sb.Append(_assessment3);
			sb.Append(_creator);
			sb.Append(_createTime);
            sb.Append(_isChief);
            sb.Append(_candidatePostGrade);
            sb.Append(_candidateManagerGrade);
            sb.Append(_candidatePost);
            sb.Append(_status);
            sb.Append(_initTime);
            sb.Append(_initor);
            sb.Append(_isPresident);
            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 员工编号
        /// </summary>
		public virtual string Code
        {
            get { return  _code; }
			set	{	_code =  value;}
        }
		
		/// <summary>
        /// 目标后备
        /// </summary>
		public virtual string TargetCandidate
        {
            get { return  _targetCandidate; }
			set	{	_targetCandidate =  value;}
        }
		
		/// <summary>
        /// 任现职时间
        /// </summary>
		public virtual string InPostDate
        {
            get { return  _inPostDate; }
			set	{	_inPostDate =  value;}
        }
		
		/// <summary>
        /// 任现级时间
        /// </summary>
		public virtual string InGradeDate
        {
            get { return  _inGradeDate; }
			set	{	_inGradeDate =  value;}
        }
		
		/// <summary>
        /// 任现级年限
        /// </summary>
		public virtual int Tenure
        {
            get { return  _tenure; }
			set	{	_tenure =  value;}
        }
		
		/// <summary>
        /// 后备成熟度
        /// </summary>
		public virtual string CandidateMaturity
        {
            get { return  _candidateMaturity; }
			set	{	_candidateMaturity =  value;}
        }
		
		/// <summary>
        /// 后备排名
        /// </summary>
		public virtual int CandidateOrder
        {
            get { return  _candidateOrder; }
			set	{	_candidateOrder =  value;}
        }
		
		/// <summary>
        /// 民主推荐率
        /// </summary>
        public virtual double DemocracyPecent
        {
            get { return _democracyPecent; }
            set { _democracyPecent = value; }
        }
		
		/// <summary>
        /// 是否破格推荐
        /// </summary>
		public virtual short IsAnomalous
        {
            get { return  _isAnomalous; }
			set	{	_isAnomalous =  value;}
        }
		
		/// <summary>
        /// 考核结果1
        /// </summary>
		public virtual string Assessment1
        {
            get { return  _assessment1; }
			set	{	_assessment1 =  value;}
        }
		
		/// <summary>
        /// 考核结果2
        /// </summary>
		public virtual string Assessment2
        {
            get { return  _assessment2; }
			set	{	_assessment2 =  value;}
        }
		
		/// <summary>
        /// 考核结果3
        /// </summary>
		public virtual string Assessment3
        {
            get { return  _assessment3; }
			set	{	_assessment3 =  value;}
        }
		
		/// <summary>
        /// 创建者
        /// </summary>
		public virtual string Creator
        {
            get { return  _creator; }
			set	{	_creator =  value;}
        }
		
		/// <summary>
        /// 创建时间
        /// </summary>
		public virtual System.DateTime CreateTime
        {
            get { return  _createTime.ToSafeDateTime(); }
			set	{	_createTime =  value.ToSafeDateTime();}
        }

        /// <summary>
        /// 是否正职
        /// </summary>
        public virtual short IsChief
        {
            get { return _isChief; }
            set { _isChief = value; }
        }

        /// <summary>
        /// 
        /// </summary>
        public virtual string CandidatePostGrade
        {
            get { return _candidatePostGrade; }
            set { _candidatePostGrade = value; }
        }

        /// <summary>
        /// 经理级别
        /// </summary>
        public virtual string CandidateManagerGrade
        {
            get { return _candidateManagerGrade; }
            set { _candidateManagerGrade = value; }
        }

        /// <summary>
        /// 后备岗位
        /// </summary>
        public virtual string CandidatePost
        {
            get { return _candidatePost; }
            set { _candidatePost = value; }
        }

        /// <summary>
        /// 状态
        /// </summary>
        public virtual short Status
        {
            get { return _status; }
            set { _status = value; }
        }

        /// <summary>
        /// 入库时间
        /// </summary>
        public virtual DateTime InitTime
        {
            get { return _initTime; }
            set { _initTime = value; }
        }

        /// <summary>
        /// 入库员
        /// </summary>
        public virtual string Initor
        {
            get { return _initor; }
            set { _initor = value; }
        }

        /// <summary>
        /// 是否县分总经理后备
        /// </summary>
        public virtual short IsPresident
        {
            get { return _isPresident; }
            set { _isPresident = value; }
        }
		
        #endregion
    }
}
