#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: LAMS
 * Module:  FamilyMember
 * Descrption:
 * CreateDate: 2010/11/18 14:11:17
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.LAMS.Domain
{
    public partial class FamilyMember :DomainObject<string>
    {
        #region Fields
		
		private string _employeeID = string.Empty;
		private string _memberRelation = string.Empty;
		private string _name = string.Empty;
		private string _gender = string.Empty;
		private string _birthDay = string.Empty;
		private string _companyAndPosition = string.Empty;
		private string _creator = string.Empty;
		private System.DateTime _createTime = DateTime.Now;
		
		
        #endregion

        #region Constructors
		public FamilyMember(){}
		
		
		public FamilyMember(string id,string employeeID,string memberRelation,string name,string gender,string birthDay,string companyAndPosition,string creator,System.DateTime createTime)
		{
		  this.ID=id;
		this._employeeID=employeeID;
		this._memberRelation=memberRelation;
		this._name=name;
		this._gender=gender;
		this._birthDay=birthDay;
		this._companyAndPosition=companyAndPosition;
		this._creator=creator;
		this._createTime=createTime;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_employeeID);
			sb.Append(_memberRelation);
			sb.Append(_name);
			sb.Append(_gender);
			sb.Append(_birthDay);
			sb.Append(_companyAndPosition);
			sb.Append(_creator);
			sb.Append(_createTime);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 员工编号
        /// </summary>
		public virtual string EmployeeID
        {
            get { return  _employeeID; }
			set	{	_employeeID =  value;}
        }
		
		/// <summary>
        /// 称谓
        /// </summary>
		public virtual string MemberRelation
        {
            get { return  _memberRelation; }
			set	{	_memberRelation =  value;}
        }
		
		/// <summary>
        /// 姓名
        /// </summary>
		public virtual string Name
        {
            get { return  _name; }
			set	{	_name =  value;}
        }
		
		/// <summary>
        /// 性别
        /// </summary>
		public virtual string Gender
        {
            get { return  _gender; }
			set	{	_gender =  value;}
        }
		
		/// <summary>
        /// 出生年月
        /// </summary>
		public virtual string BirthDay
        {
            get { return  _birthDay; }
			set	{	_birthDay =  value;}
        }
		
		/// <summary>
        /// 工作单位及职位
        /// </summary>
		public virtual string CompanyAndPosition
        {
            get { return  _companyAndPosition; }
			set	{	_companyAndPosition =  value;}
        }
		
		/// <summary>
        /// 创建者
        /// </summary>
		public virtual string Creator
        {
            get { return  _creator; }
			set	{	_creator =  value;}
        }
		
		/// <summary>
        /// 创建时间
        /// </summary>
		public virtual System.DateTime CreateTime
        {
            get { return  _createTime.ToSafeDateTime(); }
			set	{	_createTime =  value.ToSafeDateTime();}
        }
		
        #endregion
    }
}
