#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: LAMS
 * Module:  PostExperience
 * Descrption:
 * CreateDate: 2010/11/18 14:11:17
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.LAMS.Domain
{
    public partial class PostExperience :DomainObject<string>
    {
        #region Fields
		
		private string _employeeID = string.Empty;
		private string _postDate = string.Empty;
		private string _position = string.Empty;
		private string _postGrade = string.Empty;
		private string _appointDocNumber = string.Empty;
		private string _creator = string.Empty;
		private System.DateTime _createTime = DateTime.Now;
		
		
        #endregion

        #region Constructors
		public PostExperience(){}
		
		
		public PostExperience(string id,string employeeID,string postDate,string position,string postGrade,string appointDocNumber,string creator,System.DateTime createTime)
		{
		  this.ID=id;
		this._employeeID=employeeID;
		this._postDate=postDate;
		this._position=position;
		this._postGrade=postGrade;
		this._appointDocNumber=appointDocNumber;
		this._creator=creator;
		this._createTime=createTime;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_employeeID);
			sb.Append(_postDate);
			sb.Append(_position);
			sb.Append(_postGrade);
			sb.Append(_appointDocNumber);
			sb.Append(_creator);
			sb.Append(_createTime);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 员工编号
        /// </summary>
		public virtual string EmployeeID
        {
            get { return  _employeeID; }
			set	{	_employeeID =  value;}
        }
		
		/// <summary>
        /// 任职时间
        /// </summary>
		public virtual string PostDate
        {
            get { return  _postDate; }
			set	{	_postDate =  value;}
        }
		
		/// <summary>
        /// 职务名称
        /// </summary>
		public virtual string Position
        {
            get { return  _position; }
			set	{	_position =  value;}
        }
		
		/// <summary>
        /// 职务等级
        /// </summary>
		public virtual string PostGrade
        {
            get { return  _postGrade; }
			set	{	_postGrade =  value;}
        }
		
		/// <summary>
        /// 任职文号
        /// </summary>
		public virtual string AppointDocNumber
        {
            get { return  _appointDocNumber; }
			set	{	_appointDocNumber =  value;}
        }
		
		/// <summary>
        /// 创建者
        /// </summary>
		public virtual string Creator
        {
            get { return  _creator; }
			set	{	_creator =  value;}
        }
		
		/// <summary>
        /// 创建时间
        /// </summary>
		public virtual System.DateTime CreateTime
        {
            get { return  _createTime.ToSafeDateTime(); }
			set	{	_createTime =  value.ToSafeDateTime();}
        }
		
        #endregion
    }
}
