#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: LAMS
 * Module:  SupervisorCandidate
 * Descrption:
 * CreateDate: 2010/11/18 14:11:16
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.LAMS.Domain
{
    public partial class SupervisorCandidate :DomainObject<string>
    {
        #region Fields
		
		private string _supervisorID = string.Empty;
		private string _candidateManagerID = string.Empty;
		
		
        #endregion

        #region Constructors
		public SupervisorCandidate(){}
		
		
		public SupervisorCandidate(string id,string supervisorID,string candidateManagerID)
		{
		  this.ID=id;
		this._supervisorID=supervisorID;
		this._candidateManagerID=candidateManagerID;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_supervisorID);
			sb.Append(_candidateManagerID);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 导师ID
        /// </summary>
		public virtual string SupervisorID
        {
            get { return  _supervisorID; }
			set	{	_supervisorID =  value;}
        }
		
		/// <summary>
        /// 后备经理人ID
        /// </summary>
		public virtual string CandidateManagerID
        {
            get { return  _candidateManagerID; }
			set	{	_candidateManagerID =  value;}
        }
		
        #endregion
    }
}
