#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Assessment
 * Module:  AssessmentRole
 * Descrption:
 * CreateDate: 2011/01/27 14:01:00
 * Author: ljz
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.Assessment.Domain
{
   public partial class AssessmentRole :DomainObject<string>
    {
        #region Fields
		
		private string _name = string.Empty;
		private string _category = string.Empty;
		private double _weight = default(Double);
		
		
        #endregion

        #region Constructors
		public AssessmentRole(){}
		
		
		public AssessmentRole(string id,string name,string category,double weight)
		{
		  this.ID=id;
		this._name=name;
		this._category=category;
		this._weight=weight;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_name);
			sb.Append(_category);
			sb.Append(_weight);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 角色名称
        /// </summary>
		public virtual string Name
        {
            get { return  _name; }
			set	{	_name =  value;}
        }
		
		/// <summary>
        /// 360测评=1;
   
        /// </summary>
		public virtual string Category
        {
            get { return  _category; }
			set	{	_category =  value;}
        }
		
		/// <summary>
        /// 评测权重
        /// </summary>
		public virtual double Weight
        {
            get { return  _weight; }
			set	{	_weight =  value;}
        }
		
        #endregion
    }
}