#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Assessment
 * Module:  SurveyResult
 * Descrption:
 * CreateDate: 2010/11/18 14:01:00
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.Assessment.Domain
{
    public partial class Expert : DomainObject<string>
    {
        #region Fields

        private string _surveyID = string.Empty;
        private string _tester = string.Empty;
        private string _scorer = string.Empty;
        private short _status = default(Int16);
        private string _ownerOrg = string.Empty;
        private System.DateTime _createTime = DateTime.Now;
        private short _isLock = default(Int16);
        #endregion

        #region Constructors
        public Expert() { }


        public Expert(string id, string surveyID, string tester, string scorer, System.DateTime scoreTime, short status, short isLock, string ownerOrg, System.DateTime creatTime)
        {
            this.ID = id;
            this._surveyID = surveyID;
            this._tester = tester;
            this._isLock = isLock;
            this._scorer = scorer;
            this._status = status;
            this._ownerOrg = ownerOrg;
            this._createTime = creatTime;
        }
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();

            sb.Append(this.GetType().FullName);
            sb.Append(_surveyID);
            sb.Append(_tester);
            sb.Append(_scorer);
            sb.Append(_status);
            sb.Append(_ownerOrg);
            sb.Append(_createTime);
            sb.Append(_isLock);
            return sb.ToString().GetHashCode();
        }

        public virtual bool Validate()
        {
            return true;
        }

        #endregion

        #region Properties

     
        /// <summary>
        /// 测评活动ID
        /// </summary>
        public virtual string SurveyID
        {
            get { return _surveyID; }
            set { _surveyID = value; }
        }

        /// <summary>
        /// 测评人
        /// </summary>
        public virtual string Tester
        {
            get { return _tester; }
            set { _tester = value; }
        }

       

        /// <summary>
        /// 评分人
        /// </summary>
        public virtual string Scorer
        {
            get { return _scorer; }
            set { _scorer = value; }
        }

        

        /// <summary>
        /// 初始化=0;
        ///在正测试=1;
        // 完成=2;
        /// 超时=3;
        /// </summary>
        public virtual short Status
        {
            get { return _status; }
            set { _status = value; }
        }

        /// <summary>
        /// 归属组织
        /// </summary>
        public virtual string OwnerOrg
        {
            get { return _ownerOrg; }
            set { _ownerOrg = value; }
        }

        /// <summary>
        /// 测评开始时间
        /// </summary>
        public virtual System.DateTime StartTime
        {
            get { return _createTime.ToSafeDateTime(); }
            set { _createTime = value.ToSafeDateTime(); }
        }

        /// <summary>
        /// 测评结束时间
        /// </summary>
        public virtual System.DateTime CreateTime
        {
            get { return _createTime.ToSafeDateTime(); }
            set { _createTime = value.ToSafeDateTime(); }
        }

        /// <summary>
        /// 是否锁定
        /// </summary>
        public virtual short IsLock
        {
            get { return _isLock; }
            set { _isLock = value; }
        }
        #endregion
    }
}
