#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Assessment
 * Module:  SurveyResult
 * Descrption:
 * CreateDate: 2010/11/18 14:01:00
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.Assessment.Domain
{
    public partial class SurveyResult : DomainObject<string>
    {
        #region Fields

        private string _surveyID = string.Empty;
        private string _tester = string.Empty;
        private double _score = default(Double);
        private string _comment = string.Empty;
        private string _scorer = string.Empty;
        private System.DateTime _scoreTime = DateTime.Now;
        private short _status = default(Int16);
        private short _isLock = default(Int16);
        private string _ownerOrg = string.Empty;
        private System.DateTime _startTime = DateTime.Now;
        private System.DateTime _entTime = DateTime.Now;
        private string _assessmentRoleID = string.Empty;
            private int _remainTime = default(Int32);
        #endregion

        #region Constructors
        public SurveyResult() { }


        public SurveyResult(string id, string surveyID, string tester, double score, string comment, string scorer, System.DateTime scoreTime, short status, short isLock, string ownerOrg, System.DateTime startTime, System.DateTime entTime, int remainTime, string assessmentRoleID)
        {
            this.ID = id;
            this._surveyID = surveyID;
            this._tester = tester;
            this._score = score;
            this._comment = comment;
            this._scorer = scorer;
            this._scoreTime = scoreTime;
            this._status = status;
            this._isLock = isLock;
            this._ownerOrg = ownerOrg;
            this._startTime = startTime;
            this._entTime = entTime;
            this._remainTime = remainTime;
            this._assessmentRoleID = assessmentRoleID;
        }
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();

            sb.Append(this.GetType().FullName);
            sb.Append(_surveyID);
            sb.Append(_tester);
            sb.Append(_score);
            sb.Append(_comment);
            sb.Append(_scorer);
            sb.Append(_scoreTime);
            sb.Append(_status);
            sb.Append(_isLock);
            sb.Append(_ownerOrg);
            sb.Append(_startTime);
            sb.Append(_entTime);
            sb.Append(_remainTime);
            sb.Append(_assessmentRoleID);
            return sb.ToString().GetHashCode();
        }

        public virtual bool Validate()
        {
            return true;
        }

        #endregion

        #region Properties

        /// <summary>
        /// 测评剩余时间
        /// </summary>
        public virtual int RemainTime
        {
            get { return _remainTime; }
            set { _remainTime = value; }
        }

        /// <summary>
        /// 角色ID
        /// </summary>
        public virtual string AssessmentRoleID
        {
            get { return _assessmentRoleID; }
            set { _assessmentRoleID = value; }
        }
        
        /// <summary>
        /// 测评活动ID
        /// </summary>
        public virtual string SurveyID
        {
            get { return _surveyID; }
            set { _surveyID = value; }
        }

        /// <summary>
        /// 测评人
        /// </summary>
        public virtual string Tester
        {
            get { return _tester; }
            set { _tester = value; }
        }

        /// <summary>
        /// 测评分数
        /// </summary>
        public virtual double Score
        {
            get { return _score; }
            set { _score = value; }
        }

        /// <summary>
        /// 测评评语
        /// </summary>
        public virtual string Comment
        {
            get { return _comment; }
            set { _comment = value; }
        }

        /// <summary>
        /// 评分人
        /// </summary>
        public virtual string Scorer
        {
            get { return _scorer; }
            set { _scorer = value; }
        }

        /// <summary>
        /// 评分时间
        /// </summary>
        public virtual System.DateTime ScoreTime
        {
            get { return _scoreTime.ToSafeDateTime(); }
            set { _scoreTime = value.ToSafeDateTime(); }
        }

        /// <summary>
        /// 初始化=0;
        ///在正测试=1;
        // 完成=2;
        /// 超时=3;
        /// </summary>
        public virtual short Status
        {
            get { return _status; }
            set { _status = value; }
        }

        /// <summary>
        /// 是否锁定
        /// </summary>
        public virtual short IsLock
        {
            get { return _isLock; }
            set { _isLock = value; }
        }

        /// <summary>
        /// 归属组织
        /// </summary>
        public virtual string OwnerOrg
        {
            get { return _ownerOrg; }
            set { _ownerOrg = value; }
        }

        /// <summary>
        /// 测评开始时间
        /// </summary>
        public virtual System.DateTime StartTime
        {
            get { return _startTime.ToSafeDateTime(); }
            set { _startTime = value.ToSafeDateTime(); }
        }

        /// <summary>
        /// 测评结束时间
        /// </summary>
        public virtual System.DateTime EntTime
        {
            get { return _entTime.ToSafeDateTime(); }
            set { _entTime = value.ToSafeDateTime(); }
        }

        #endregion
    }
}
