#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Assessment
 * Module:  SurveyResult
 * Descrption:
 * CreateDate: 2010/11/18 14:01:00
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Reflection;
using System.Data;
using System.Collections;
using System.Text;

using Microsoft.Practices.Unity;
using log4net;
using EAFrame.Core;
using EAFrame.Core.Enums;
using EAFrame.Core.Service;
using EAFrame.Core.Security;
using EAFrame.Core.Utility;
using EAFrame.Core.Extensions;
using EAFrame.Core.Web;
using EAFrame.Core.Caching;
using EAFrame.Core.FastInvoker;
using EAFrame.Core.DataFilter;
using EAFrame.WebControls;
using SunTek.Assessment.Domain;
using SunTek.Assessment.Service;
using SunTek.EAFrame.AuthorizeCenter.Domain;
using SunTek.EAFrame.AuthorizeCenter.Service;
using EAFrame.Core.Data;

namespace WebSite
{
    public partial class ExpertProcess : BasePage
    {
        private SurveyResultService surveyResultService = new SurveyResultService();
        private ExpertService expertService = new ExpertService();
        #region ---界面处理方法---

      

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                ShowList();
            }
        }

        #endregion

        #region ---操作处理方法---
      

        /// <summary>
        /// 显示列表信息
        /// </summary>
        /// <param name="gvList">GridView对象</param>
        /// <param name="pageInfo">分页信息</param>
        public void ShowList()
        {
            //IPageOfList<SurveyResult> result = surveyResultService.FindAll(GetFilterParameters(), pageInfo);
            //IDictionary<string, object> para = new Dictionary<string, object>();

            //if (!string.IsNullOrWhiteSpace(CurrentId))
            //{
            //    para.SafeAdd("SurveyID", CurrentId);
            //}

            //IPageOfList<SurveyResult> result = surveyResultService.FindAll(para, pageInfo);
            //gvList.ItemCount = result.PageInfo.ItemCount;
            //gvList.DataSource = result;
            //gvList.DataBind();
            StringBuilder html = new StringBuilder();
            StringBuilder headHtml = new StringBuilder();
            StringBuilder ctnHtml = new StringBuilder();



            html.Append("<table cellspacing=\"0\" border=\"1\" style=\"width:100%;border-collapse:collapse;\">");

            IDictionary<string, object> para = new Dictionary<string, object>();

            if (!string.IsNullOrWhiteSpace(CurrentId))
            {
                Survey survey = new SurveyService().GetDomain(CurrentId);

                para.SafeAdd("SurveyID", CurrentId);
                IList<SurveyResult> surveyResults = surveyResultService.FindAll(para).ToList();
                para.Clear();
                para.SafeAdd("AssessmentResultID", new EAFrame.Core.Data.Condition(string.Format("(AssessmentResultID in (select ID from LA_SurveyResult where SurveyID='{0}'))", CurrentId)));
                IList<AnswerRecord> answerRecords = new AnswerRecordService().FindAll(para).ToList();
                if (answerRecords.Count == 0)
                {
                    WebUtil.PromptMsg("该问卷还没有任何评分人进行打分或还未添加任何评分人！");
                    WebUtil.CloseWidow(true);
                    return;
                }

                
                List<Subject> subjects = new ExamPaperService().GetSubjectByExamPaper(survey.ExamPaperID);  //获取问卷题目
                //获取专家列表

                DataTable dtExperts = expertService.GetSurveyExpert(survey.ID);

                 para = new Dictionary<string, object>();
                para.SafeAdd("Tester", new Condition("a.Tester!='-1'"));
                para.SafeAdd("SurveyID", new Condition(string.Format("a.SurveyID='{0}'", survey.ID)));
                DataTable dtExpertStatus = expertService.GetSurveyExpert(para,null);

                //制作表头
                headHtml.AppendFormat("<tr class='th'><td rowspan=2>员工编号</td><td rowspan=2>姓名</td>");

                StringBuilder subHeadHtml = new StringBuilder("");

                foreach (DataRow dr  in dtExperts.Rows)
                {
                        headHtml.AppendFormat("<td rowspan=2>{0}</td>",dr["Name"]);
                }
                headHtml.Append("</tr>");
                headHtml.AppendFormat("<tr class='th'>{0}</tr>", subHeadHtml.ToSafeString());

                foreach (SurveyResult surveyResult in surveyResults)
                {

                    ctnHtml.Append("<tr>");
                    Employee employee = new EmployeeService().GetDomain(surveyResult.Tester);

                    ctnHtml.AppendFormat("<td>{0}</td><td>{1}</td>", employee.Code, employee.Name);

                    foreach (DataRow dr in dtExperts.Rows)
                    {
                        string statusStr = string.Empty;

                        foreach (DataRow dr2 in dtExpertStatus.Rows)
                        {
                            if (dr2["Tester"].ToSafeString() == surveyResult.Tester && dr2["Scorer"].ToSafeString() == dr["Scorer"].ToSafeString()&&dr2["Status"].ToSafeString()=="2")
                            {
                                statusStr = string.Format("<a  ondblclick=\"rowDbClick(this)\" title='双击进行评分详细查看' href='javascript:void(0)' id='{1}'>{0}</a>", "已评分", dr2["ID"]);
                            }
                        }
                        ctnHtml.AppendFormat("<td>{0}</td>", statusStr);
                      // if(dr2["Tester"]==surveyResult.Tester&&)
                    }

                     

                    ctnHtml.Append("</tr>");

                }


                html.AppendFormat("{0}{1}</table>", headHtml, ctnHtml);
                litTable.Text = html.ToSafeString();

            }
        }

      

        
        #endregion
    }
}
