#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Workflow
 * Module:  ProcessInst
 * Descrption:
 * CreateDate: 2010/11/18 12:00:10
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Reflection;

using log4net;
using Microsoft.Practices.Unity;
using EAFrame.Core;
using EAFrame.Core.Enums;
using EAFrame.Core.Service;
using EAFrame.Core.Security;
using EAFrame.Core.Extensions;
using EAFrame.Core.Web;
using EAFrame.Core.Caching;
using EAFrame.Core.Utility;
using EAFrame.Core.FastInvoker;
using EAFrame.WebControls;
using EAFrame.Workflow.Domain;
using EAFrame.Workflow.Service;

namespace WebSite
{
    public partial class ProcessInstDetail : BasePage
    {
        private ProcessInstService processInstService=new ProcessInstService();
		
		#region ---界面处理方法---

       	protected bool ShowPageDetail()
        {
			if (PageContext.Action == ActionType.Add)
			{
				dtpLimitTime.Text=DateTime.Now.ToShortDateString();
				dtpStartTime.Text=DateTime.Now.ToShortDateString();
				dtpEndTime.Text=DateTime.Now.ToShortDateString();
				dtpFinalTime.Text=DateTime.Now.ToShortDateString();
				dtpRemindTime.Text=DateTime.Now.ToShortDateString();
				dtpTimeOutTime.Text=DateTime.Now.ToShortDateString();
				dtpCreateTime.Text=DateTime.Now.ToShortDateString();
				return false;
			}

            ProcessInst entity =processInstService.GetDomain(CurrentId);
			
            if (entity == null) return false;

			SetControlValues(entity);
			
			return true;
        }
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                ShowPageDetail();
            }
        }
		#endregion
		
		#region ---操作处理方法---
		protected ProcessInst GetDomainObject()
		{
            ProcessInst  processInst = processInstService.GetDomain(CurrentId);

            if (processInst == null)
            {
                processInst = new ProcessInst();
				processInst.ID=CurrentId;
            }

			GetControlValues(ref processInst);	
			
            return processInst;
		}

		#endregion
    }
}
