#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: ExternalInterface
 * Module:  MessagePump
 * Descrption:
 * CreateDate: 2010/11/18 13:45:01
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Data;
using System.Collections.Generic;
using log4net;

using EAFrame.Core;
using EAFrame.Core.Caching;
using EAFrame.Core.Service;
using EAFrame.Core.Enums;
using EAFrame.Core.DataFilter;
using SunTek.EAFrame.ExternalInterface.Domain;

namespace SunTek.EAFrame.ExternalInterface.Service
{
    public class MessagePumpService :  BaseService<string,MessagePump>
    {
		#region Fields
		private readonly ILog log = LogManager.GetLogger(typeof(MessagePumpService));
		#endregion
		
		#region Constructors
		
		public MessagePumpService(){ }
		#endregion

        #region IMessagePumpService Imp

        #endregion
		
		#region Internal Methods

        #endregion
    }
}