#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: LAMS
 * Module:  CandidateManager
 * Descrption:
 * CreateDate: 2010/11/18 14:11:17
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Reflection;

using log4net;
using Microsoft.Practices.Unity;
using EAFrame.Core;
using EAFrame.Core.Enums;
using EAFrame.Core.Service;
using EAFrame.Core.Security;
using EAFrame.Core.Extensions;
using EAFrame.Core.Web;
using EAFrame.Core.Caching;
using EAFrame.Core.Utility;
using EAFrame.Core.FastInvoker;
using EAFrame.WebControls;
using SunTek.LAMS.Domain;
using SunTek.LAMS.Service;

namespace WebSite
{
    public partial class CandidateManagerDetail : BasePage
    {
        private CandidateManagerService candidateManagerService=new CandidateManagerService();

        public string Grade
        {
            get
            {
                return Request.QueryString["grade"] ?? "grade2";
            }
        }

        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack)
            {
                ShowPageDetail();
            }
        }
        
		#region ---界面处理方法---

       	protected bool ShowPageDetail()
        {
			if (PageContext.Action == ActionType.Add)
			{
				dtpCreateTime.Text=DateTime.Now.ToShortDateString();
				return false;
			}

            CandidateManager entity =candidateManagerService.GetDomain(CurrentId);
			
            if (entity == null) return false;

			SetControlValues(entity);
			
			return true;
        }
		#endregion
		
		#region ---操作处理方法---
		protected CandidateManager GetDomainObject()
		{
            CandidateManager  candidateManager = candidateManagerService.GetDomain(CurrentId);

            if (candidateManager == null)
            {
                candidateManager = new CandidateManager();
				candidateManager.ID=CurrentId;
            }

			GetControlValues(ref candidateManager);	
			
            return candidateManager;
		}

        public void Save(string argument)
        {
            try
            {
                CandidateManager candidateManager = GetDomainObject();
                candidateManagerService.SaveOrUpdate(candidateManager);

                WebUtil.PromptMsg("保存操作成功");
            }
            catch (Exception ex)
            {
                log.Error("保存操作失败", ex);

                WebUtil.PromptMsg("保存操作失败");
            }
        }

		#endregion
    }
}
