#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: ExternalInterface
 * Module:  ArchiveMessage
 * Descrption:
 * CreateDate: 2010/11/18 13:45:01
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.UI;
using System.Web.UI.WebControls;
using System.Reflection;

using log4net;
using Microsoft.Practices.Unity;
using EAFrame.Core;
using EAFrame.Core.Enums;
using EAFrame.Core.Service;
using EAFrame.Core.Security;
using EAFrame.Core.Extensions;
using EAFrame.Core.Web;
using EAFrame.Core.Caching;
using EAFrame.Core.Utility;
using EAFrame.Core.FastInvoker;
using EAFrame.WebControls;
using SunTek.EAFrame.ExternalInterface.Domain;
using SunTek.EAFrame.ExternalInterface.Service;

namespace WebSite
{
    public partial class ArchiveMessageDetail : BasePage
    {
        private ArchiveMessageService archiveMessageService=new ArchiveMessageService();
		
		#region ---界面处理方法---

       	protected bool ShowPageDetail()
        {
			if (PageContext.Action == ActionType.Add)
			{
				dtpArchiveTime.Text=DateTime.Now.ToShortDateString();
				return false;
			}

            ArchiveMessage entity =archiveMessageService.GetDomain(CurrentId);
			
            if (entity == null) return false;

			SetControlValues(entity);
			
			return true;
        }
        protected void Page_Load(object sender, EventArgs e)
        {
            if (!IsPostBack && !IsAjaxPost)
            {
                ShowPageDetail();
            }
        }
		#endregion
		
		#region ---操作处理方法---
		protected ArchiveMessage GetDomainObject()
		{
            ArchiveMessage  archiveMessage = archiveMessageService.GetDomain(CurrentId);

            if (archiveMessage == null)
            {
                archiveMessage = new ArchiveMessage();
				archiveMessage.ID=CurrentId;
            }

			GetControlValues(ref archiveMessage);	
			
            return archiveMessage;
		}

		#endregion
    }
}
