#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Assessment
 * Module:  AssessmentRole
 * Descrption:
 * CreateDate: 2011/01/27 14:01:00
 * Author: ljz
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.Assessment.Domain
{
   public partial class AssessmentRoleWeight :DomainObject<string>
    {
        #region Fields
		
		
        private string _roleID = string.Empty;
        private string _surveyID = string.Empty;
		private double _weight = default(Double);
		
		
        #endregion

        #region Constructors
		public AssessmentRoleWeight(){}


        public AssessmentRoleWeight(string id, string surveyID, string roleID, double weight)
		{
		  this.ID=id;
		this.SurveyID=_surveyID;
		this.RoleID=_roleID;
		this._weight=weight;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_surveyID);
			sb.Append(_roleID);
			sb.Append(_weight);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 测评ID
        /// </summary>
		public virtual string SurveyID
        {
            get { return  _surveyID; }
            set { _surveyID = value; }
        }
		
		/// <summary>
        /// 角色
   
        /// </summary>
		public virtual string RoleID
        {
            get { return  _roleID; }
            set { _roleID = value; }
        }
		
		/// <summary>
        /// 评测权重
        /// </summary>
		public virtual double Weight
        {
            get { return  _weight; }
			set	{	_weight =  value;}
        }
		
        #endregion
    }
}