#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Assessment
 * Module:  ExamPaper
 * Descrption:
 * CreateDate: 2010/11/18 14:00:59
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.Assessment.Domain
{
    public partial class ExamPaper : DomainObject<string>
    {
        #region Fields

        private string _title = string.Empty;
        private string _description = string.Empty;
        private short _category = default(Int16);
        private int _defaultScore = default(Int32);
        private string _ownerOrg = string.Empty;
        private string _creator = string.Empty;
        private System.DateTime _createTime = DateTime.Now;


        #endregion

        #region Constructors
        public ExamPaper() { }


        public ExamPaper(string id, string title, string description, short category, int defaultScore, string ownerOrg, string creator, System.DateTime createTime)
        {
            this.ID = id;
            this._title = title;
            this._description = description;
            this._category = category;
            this._defaultScore = defaultScore;
            this._ownerOrg = ownerOrg;
            this._creator = creator;
            this._createTime = createTime;
        }
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();

            sb.Append(this.GetType().FullName);
            sb.Append(_title);
            sb.Append(_description);
            sb.Append(_category);
            sb.Append(_defaultScore);
            sb.Append(_ownerOrg);
            sb.Append(_creator);
            sb.Append(_createTime);

            return sb.ToString().GetHashCode();
        }

        public virtual bool Validate()
        {
            return true;
        }

        #endregion

        #region Properties

        /// <summary>
        /// 试卷标题
        /// </summary>
        public virtual string Title
        {
            get { return _title; }
            set { _title = value; }
        }

        /// <summary>
        /// 说明
        /// </summary>
        public virtual string Description
        {
            get { return _description; }
            set { _description = value; }
        }

        /// <summary>
        /// 360测评=1;
        /// 动机测评=2;
        /// 团队效能测评=3;
        /// 优势与特点测评=4;
        /// Disc测评=5;
        /// 情景模拟=21;
        /// 案例分析=22;
        /// 关键事件访谈=23;
        /// </summary>
        public virtual short Category
        {
            get { return _category; }
            set { _category = value; }
        }

        /// <summary>
        /// 默认分值
        /// </summary>
        public virtual int DefaultScore
        {
            get { return _defaultScore; }
            set { _defaultScore = value; }
        }

        /// <summary>
        /// 归属组织
        /// </summary>
        public virtual string OwnerOrg
        {
            get { return _ownerOrg; }
            set { _ownerOrg = value; }
        }

        /// <summary>
        /// 创建者
        /// </summary>
        public virtual string Creator
        {
            get { return _creator; }
            set { _creator = value; }
        }

        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual System.DateTime CreateTime
        {
            get { return _createTime.ToSafeDateTime(); }
            set { _createTime = value.ToSafeDateTime(); }
        }

        #endregion

        public virtual List<ExamPaperSubject> ExamPaperSubjects
        {
            get;
            set;
        }

        public virtual List<MainSubject> ExamMainSubjects
        {
            get;
            set;
        }

    }
}
