#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Assessment
 * Module:  ExamPaperSubject
 * Descrption:
 * CreateDate: 2010/11/18 14:00:59
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.Assessment.Domain
{
    public partial class ExamPaperSubject :DomainObject<string>
    {
        #region Fields
		
		private string _subjectID = string.Empty;
		private string _examPaperID = string.Empty;
        private int _sortOrder = default(Int32);
        private string _mainSubjectID = string.Empty;
        private int _subjectScore = default(Int32);
        #endregion

        #region Constructors
		public ExamPaperSubject(){}


        public ExamPaperSubject(string id, string subjectID, string examPaperID, int sortOrder, string mainSubjectID, int subjectScore)
		{
		  this.ID=id;
		this._subjectID=subjectID;
		this._examPaperID=examPaperID;
        this._sortOrder = sortOrder;
        this._mainSubjectID = mainSubjectID;
        this._subjectScore = subjectScore;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_subjectID);
			sb.Append(_examPaperID);
            sb.Append(_sortOrder);
            sb.Append(_mainSubjectID);

            return sb.ToString().GetHashCode();
        }
        /// <summary>
        /// 
        /// </summary>
        public virtual int SubjectScore
        {
            get { return _subjectScore; }
            set { _subjectScore = value; }
        }
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties

        public virtual int SortOrder
        {
            get { return _sortOrder; }
            set { _sortOrder = value; }
        }

		/// <summary>
        /// 题目ID
        /// </summary>
		public virtual string SubjectID
        {
            get { return  _subjectID; }
			set	{	_subjectID =  value;}
        }

        /// <summary>
        /// 大题
        /// </summary>
        public virtual string MainSubjectID
        {
            get { return  _mainSubjectID; }
			set	{	_mainSubjectID =  value;}
        }
		

		/// <summary>
        /// 试卷ID
        /// </summary>
		public virtual string ExamPaperID
        {
            get { return  _examPaperID; }
			set	{	_examPaperID =  value;}
        }
		
        #endregion
    }
}
