#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Assessment
 * Module:  SubjectItem
 * Descrption:
 * CreateDate: 2010/11/18 14:01:00
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.Assessment.Domain
{
    public partial class SubjectItem :DomainObject<string>
    {
        #region Fields
		
		private string _subjectID = string.Empty;
		private string _itemTitle = string.Empty;
		private int _itemScore =0;
        private string _nextSubjectID = string.Empty;
		private int _sortOrder = default(Int32);
        private int _dim = default(Int32);
		
        #endregion

        #region Constructors
		public SubjectItem(){}


        public SubjectItem(string id, string subjectID, string itemTitle, int itemScore, int sortOrder, string nextSubjectID,int dim)
		{
		  this.ID=id;
		this._subjectID=subjectID;
		this._itemTitle=itemTitle;
        this._itemScore = itemScore;
		this._sortOrder=sortOrder;
        this._nextSubjectID = nextSubjectID;
        this._dim = dim;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_subjectID);
			sb.Append(_itemTitle);
			sb.Append(_itemScore);
			sb.Append(_sortOrder);
            sb.Append(_nextSubjectID);
            sb.Append(_dim);
            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 题目ID
        /// </summary>
		public virtual string SubjectID
        {
            get { return  _subjectID; }
			set	{	_subjectID =  value;}
        }

        public virtual string NextSubjectID
        {

            get { return _nextSubjectID; }
            set { _nextSubjectID = value; }
        }

		/// <summary>
        /// 选项标题
        /// </summary>
		public virtual string ItemTitle
        {
            get { return  _itemTitle; }
			set	{	_itemTitle =  value;}
        }
		
		/// <summary>
        /// 选项值
        /// </summary>
		public virtual int ItemScore
        {
            get { return  _itemScore; }
			set	{	_itemScore =  value;}
        }
		
		/// <summary>
        /// 序号
        /// </summary>
		public virtual int SortOrder
        {
            get { return  _sortOrder; }
			set	{	_sortOrder =  value;}
        }

        /// <summary>
        /// 维度
        /// </summary>
        public virtual int Dim
        {
            get { return _dim; }
            set { _dim = value; }
        }
        #endregion
    }
}
