#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: EAFrame.Assessment
 * Module:  SubjectItemCore
 * Descrption:
 * CreateDate: 2011-1-27 10:50:47
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.Assessment.Domain
{
    public partial class SubjectItemCore :DomainObject<string>
    {
        #region Fields
		
		private string _examPaperID = string.Empty;
		private string _subjectID = string.Empty;
		private string _subjectItemID = string.Empty;
		private int _score = default(Int32);
		
		
        #endregion

        #region Constructors
		public SubjectItemCore(){}
		
		
		public SubjectItemCore(string id,string examPaperID,string subjectID,string subjectItemID,int score)
		{
		  this.ID=id;
		this._examPaperID=examPaperID;
		this._subjectID=subjectID;
		this._subjectItemID=subjectItemID;
		this._score=score;
		}
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();
            
            sb.Append(this.GetType().FullName);
			sb.Append(_examPaperID);
			sb.Append(_subjectID);
			sb.Append(_subjectItemID);
			sb.Append(_score);

            return sb.ToString().GetHashCode();
        }
		
		public virtual bool Validate()
        {
			return true;
        }

        #endregion

        #region Properties
		
		/// <summary>
        /// 试卷ID
        /// </summary>
		public virtual string ExamPaperID
        {
            get { return  _examPaperID; }
			set	{	_examPaperID =  value;}
        }
		
		/// <summary>
        /// 题目ID
        /// </summary>
		public virtual string SubjectID
        {
            get { return  _subjectID; }
			set	{	_subjectID =  value;}
        }
		
		/// <summary>
        /// 题目选项ID
        /// </summary>
		public virtual string SubjectItemID
        {
            get { return  _subjectItemID; }
			set	{	_subjectItemID =  value;}
        }
		
		/// <summary>
        /// 选项分值
        /// </summary>
		public virtual int Score
        {
            get { return  _score; }
			set	{	_score =  value;}
        }
		
        #endregion
    }
}
