#region Description
/*================================================================================
 *  Copyright (c) SunTek.  All rights reserved.
 * ===============================================================================
 * Solution: Assessment
 * Module:  Survey
 * Descrption:
 * CreateDate: 2010/11/18 14:01:00
 * Author: trenhui
 * Version:1.0
 * ===============================================================================
 * History
 *
 * Update Descrption:
 * Remark:
 * Update Time:
 * Author:generated by codesmithTemplate
 * 
 * ===============================================================================*/
#endregion
using System;
using System.Collections;
using System.Collections.Generic;

using EAFrame.Core.Domain;
using EAFrame.Core.Extensions;
using Newtonsoft.Json;
using Iesi.Collections.Generic;

namespace SunTek.Assessment.Domain
{
    public partial class Survey : DomainObject<string>
    {
        #region Fields

        private string _title = string.Empty;
        private string _examPaperID = string.Empty;
        private short _category = default(Int16);
        private string _ownerOrg = string.Empty;
        private int _limitTime = default(Int32);
        private System.DateTime _endTime = DateTime.Now;
        private string _creator = string.Empty;
        private System.DateTime _createTime = DateTime.Now;
        private double _comprehensiveScore = default(Double);

        private string _parentID = "-1";
        #endregion

        #region Constructors
        public Survey() { }


        public Survey(string id, string title, string examPaperID, short category, string ownerOrg, int limitTime, System.DateTime endTime, string creator, System.DateTime createTime, double comprehensiveScore, string parentID)
        {
            this.ID = id;
            this._title = title;
            this._examPaperID = examPaperID;
            this._category = category;
            this._ownerOrg = ownerOrg;
            this._limitTime = limitTime;
            this._endTime = endTime;
            this._creator = creator;
            this._createTime = createTime;
            this._comprehensiveScore = comprehensiveScore;
            this._parentID = parentID;
        }
        #endregion

        #region Methods

        public override int GetHashCode()
        {
            System.Text.StringBuilder sb = new System.Text.StringBuilder();

            sb.Append(this.GetType().FullName);
            sb.Append(_title);
            sb.Append(_examPaperID);
            sb.Append(_category);
            sb.Append(_ownerOrg);
            sb.Append(_limitTime);
            sb.Append(_endTime);
            sb.Append(_creator);
            sb.Append(_createTime);
            sb.Append(_comprehensiveScore);
            sb.Append(_parentID);
            return sb.ToString().GetHashCode();
        }

        public virtual bool Validate()
        {
            return true;
        }

        #endregion

        #region Properties

        /// <summary>
        /// 测评名称
        /// </summary>
        public virtual string Title
        {
            get { return _title; }
            set { _title = value; }
        }

        /// <summary>
        /// 试卷ID
        /// </summary>
        public virtual string ExamPaperID
        {
            get { return _examPaperID; }
            set { _examPaperID = value; }
        }

        /// <summary>
        /// 360测评=1;
        ///动机测评=2;
        ///团队效能测评=3;
        /// 优势与特点测评=4;
        ///Disc测评=5;
        ///情景模拟=21;
        ///案例分析=22;
        /// 关键事件访谈=23;
        /// </summary>
        public virtual short Category
        {
            get { return _category; }
            set { _category = value; }
        }

        /// <summary>
        /// 归属组织
        /// </summary>
        public virtual string OwnerOrg
        {
            get { return _ownerOrg; }
            set { _ownerOrg = value; }
        }

        /// <summary>
        /// 考试时间
        /// </summary>
        public virtual int LimitTime
        {
            get { return _limitTime; }
            set { _limitTime = value; }
        }

        /// <summary>
        /// 结束时间
        /// </summary>
        public virtual System.DateTime EndTime
        {
            get { return _endTime.ToSafeDateTime(); }
            set { _endTime = value.ToSafeDateTime(); }
        }

        /// <summary>
        /// 创建者
        /// </summary>
        public virtual string Creator
        {
            get { return _creator; }
            set { _creator = value; }
        }

        /// <summary>
        /// 创建时间
        /// </summary>
        public virtual System.DateTime CreateTime
        {
            get { return _createTime.ToSafeDateTime(); }
            set { _createTime = value.ToSafeDateTime(); }
        }

        /// <summary>
        /// 状态
        /// </summary>
        public virtual short Status { get; set; }

        /// <summary>
        /// 评测对象
        /// </summary>
        public virtual string SurveyTarget { get; set; }

        /// <summary>
        /// 综合评分
        /// </summary>
        public virtual double ComprehensiveScore
        {
            get { return _comprehensiveScore; }
            set { _comprehensiveScore = value; }
        }

        /// <summary>
        /// 父项id
        /// </summary>
        public virtual string ParentID
        {
            get { return _parentID; }
            set { _parentID = value; }
        }
        

        #endregion
    }
}
